In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [4]:
os.chdir(path='C:\\Users\\SDS\\Documents\\project\\data')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [5]:
os.chdir(path='../code')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [8]:
os.chdir('../data')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [9]:
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [10]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [12]:
[file for file in os.listdir() if 'iris' in file]

['iris.csv', 'iris.json', 'iris.parquet', 'iris.tsv', 'iris.xlsx']

In [13]:
df1 = pd.read_excel('iris.xlsx')
df1

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [14]:
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [16]:
df1.to_excel('test.xlsx')

In [17]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.xlsx']

In [18]:
df2 = pd.read_csv('iris.csv')
df2.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [19]:
df2.to_csv('test.csv', index=False, )

In [20]:
df3 = pd.read_csv('iris.tsv', sep='\t')
df3.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [21]:
df3.to_csv('test.tsv', index=False, sep='\t')
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.csv',
 'test.tsv',
 'test.xlsx']

In [22]:
df4 = pd.read_json('iris.json')
df4.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [26]:
from pprint import pprint

In [27]:
pprint(df4)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [28]:
df4.to_json('test.json')
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv', 'APT_Price_Seoul_Merged_2021~2025.xlsx', 'Galaxy_Book_Review_20250131.xlsx', 'Galaxy_Book_Review_20250131_Corrected.xlsx', 'iris.csv', 'iris.json', 'iris.parquet', 'iris.tsv', 'iris.xlsx', 'test.csv', 'test.json', 'test.tsv', 'test.xlsx']

In [29]:
df5 = pd.read_parquet('iris.parquet')
df5.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [30]:
df5.to_parquet('test.parquet')
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv', 'APT_Price_Seoul_Merged_2021~2025.xlsx', 'Galaxy_Book_Review_20250131.xlsx', 'Galaxy_Book_Review_20250131_Corrected.xlsx', 'iris.csv', 'iris.json', 'iris.parquet', 'iris.tsv', 'iris.xlsx', 'test.csv', 'test.json', 'test.parquet', 'test.tsv', 'test.xlsx']

In [31]:
files = [file for file in os.listdir() if 'test' in file ]

In [32]:
for file in files:
    os.remove(file)

In [33]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv', 'APT_Price_Seoul_Merged_2021~2025.xlsx', 'Galaxy_Book_Review_20250131.xlsx', 'Galaxy_Book_Review_20250131_Corrected.xlsx', 'iris.csv', 'iris.json', 'iris.parquet', 'iris.tsv', 'iris.xlsx']