In [2]:
import pandas as pd
import os, numpy as np

In [3]:
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [4]:
os.chdir('../data')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [5]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [6]:
%time apt = pd.read_excel('APT_Price_Seoul_Merged_2021~2025.xlsx')

CPU times: total: 38.7 s
Wall time: 38.7 s

In [7]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [8]:
apt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233299 entries, 0 to 233298
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   거래금액    233299 non-null  int64
 1   지역코드    233299 non-null  int64
 2   아파트     233299 non-null  object
 3   시도명     233299 non-null  object
 4   시군구     233299 non-null  object
 5   법정동     233299 non-null  object
 6   지번      233299 non-null  object
 7   건축년도    233299 non-null  int64
 8   년       233299 non-null  int64
 9   월       233299 non-null  int64
 10  일       233299 non-null  int64
 11  등기일자    165337 non-null  datetime64[ns]
 12  매도자     141486 non-null  object
 13  전용면적    233299 non-null  float64
 14  층       233299 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.7+ MB

In [13]:
#  날짜 시간형으로 읽으려면, 'yyyy-mm-dd' 형태이어야 한다. 
%time apt = pd.read_csv('APT_Price_Seoul_Merged_2021~2025.csv', parse_dates = ['등기일자'])

CPU times: total: 406 ms
Wall time: 412 ms

In [14]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [15]:
apt.tail()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
233294,48900,11260,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,개인,71.86,2
233295,49800,11260,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,개인,69.60,5
233296,83000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,개인,84.03,3
233297,72000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,개인,59.76,9
233298,71000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,개인,59.76,11

In [16]:
apt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233299 entries, 0 to 233298
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   거래금액    233299 non-null  int64
 1   지역코드    233299 non-null  int64
 2   아파트     233299 non-null  object
 3   시도명     233299 non-null  object
 4   시군구     233299 non-null  object
 5   법정동     233299 non-null  object
 6   지번      233299 non-null  object
 7   건축년도    233299 non-null  int64
 8   년       233299 non-null  int64
 9   월       233299 non-null  int64
 10  일       233299 non-null  int64
 11  등기일자    165337 non-null  datetime64[ns]
 12  매도자     141486 non-null  object
 13  전용면적    233299 non-null  float64
 14  층       233299 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.7+ MB

In [17]:
apt['지역코드']

0         11680
1         11680
2         11680
3         11680
4         11680
          ...
233294    11260
233295    11260
233296    11260
233297    11260
233298    11260
Name: 지역코드, Length: 233299, dtype: int64

In [21]:
apt.loc[:,'지역코드']

0         11680
1         11680
2         11680
3         11680
4         11680
          ...
233294    11260
233295    11260
233296    11260
233297    11260
233298    11260
Name: 지역코드, Length: 233299, dtype: int64

In [25]:
apt.iloc[:,1]

0         11680
1         11680
2         11680
3         11680
4         11680
          ...
233294    11260
233295    11260
233296    11260
233297    11260
233298    11260
Name: 지역코드, Length: 233299, dtype: int64

In [27]:
apt.loc[:, ['지역코드','거래금액']]

         지역코드    거래금액
0       11680  215000
1       11680  178000
2       11680  181000
3       11680  157000
4       11680  150000
...       ...     ...
233294  11260   48900
233295  11260   49800
233296  11260   83000
233297  11260   72000
233298  11260   71000

[233299 rows x 2 columns]

In [29]:
apt.iloc[:,[0,1]]

          거래금액   지역코드
0       215000  11680
1       178000  11680
2       181000  11680
3       157000  11680
4       150000  11680
...        ...    ...
233294   48900  11260
233295   49800  11260
233296   83000  11260
233297   72000  11260
233298   71000  11260

[233299 rows x 2 columns]

In [30]:
apt.iloc[:, np.r_[2, 3:6, 0]]

                          아파트    시도명  시군구  법정동    거래금액
0               현대1차101동~106동  서울특별시  강남구  개포동  215000
1                     개포주공6단지  서울특별시  강남구  개포동  178000
2                         우성8  서울특별시  강남구  개포동  181000
3                     삼익대청아파트  서울특별시  강남구  개포동  157000
4                  성원대치2단지아파트  서울특별시  강남구  개포동  150000
...                       ...    ...  ...  ...     ...
233294                 강오(B동)  서울특별시  중랑구  중화동   48900
233295                     태솔  서울특별시  중랑구  중화동   49800
233296  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동   83000
233297  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동   72000
233298  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동   71000

[233299 rows x 5 columns]

In [31]:
apt.loc[:, '거래금액':'법정동']

          거래금액   지역코드                    아파트    시도명  시군구  법정동
0       215000  11680          현대1차101동~106동  서울특별시  강남구  개포동
1       178000  11680                개포주공6단지  서울특별시  강남구  개포동
2       181000  11680                    우성8  서울특별시  강남구  개포동
3       157000  11680                삼익대청아파트  서울특별시  강남구  개포동
4       150000  11680             성원대치2단지아파트  서울특별시  강남구  개포동
...        ...    ...                    ...    ...  ...  ...
233294   48900  11260                 강오(B동)  서울특별시  중랑구  중화동
233295   49800  11260                     태솔  서울특별시  중랑구  중화동
233296   83000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동
233297   72000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동
233298   71000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동

[233299 rows x 6 columns]

In [32]:
apt.dtypes

거래금액             int64
지역코드             int64
아파트             object
시도명             object
시군구             object
법정동             object
지번              object
건축년도             int64
년                int64
월                int64
일                int64
등기일자    datetime64[ns]
매도자             object
전용면적           float64
층                int64
dtype: object

In [33]:
apt.dtypes == 'int64'

거래금액     True
지역코드     True
아파트     False
시도명     False
시군구     False
법정동     False
지번      False
건축년도     True
년        True
월        True
일        True
등기일자    False
매도자     False
전용면적    False
층        True
dtype: bool

In [35]:
apt.loc[:, apt.dtypes == 'int64']

          거래금액   지역코드  건축년도     년   월   일   층
0       215000  11680  1984  2021   1   1   9
1       178000  11680  1983  2021   1   1   3
2       181000  11680  1987  2021   1   3   3
3       157000  11680  1992  2021   1   4  13
4       150000  11680  1992  2021   1   4  12
...        ...    ...   ...   ...  ..  ..  ..
233294   48900  11260  2004  2025  12   6   2
233295   49800  11260  2006  2025  12  14   5
233296   83000  11260  1997  2025  12  18   3
233297   72000  11260  1997  2025  12  26   9
233298   71000  11260  1997  2025  12  27  11

[233299 rows x 7 columns]

In [38]:
apt.loc[:, (apt.dtypes == 'float64')|(apt.dtypes == 'int64')]

          거래금액   지역코드  건축년도     년   월   일   전용면적   층
0       215000  11680  1984  2021   1   1  95.40   9
1       178000  11680  1983  2021   1   1  53.06   3
2       181000  11680  1987  2021   1   3  78.93   3
3       157000  11680  1992  2021   1   4  60.00  13
4       150000  11680  1992  2021   1   4  49.86  12
...        ...    ...   ...   ...  ..  ..    ...  ..
233294   48900  11260  2004  2025  12   6  71.86   2
233295   49800  11260  2006  2025  12  14  69.60   5
233296   83000  11260  1997  2025  12  18  84.03   3
233297   72000  11260  1997  2025  12  26  59.76   9
233298   71000  11260  1997  2025  12  27  59.76  11

[233299 rows x 8 columns]

In [39]:
apt.select_dtypes(include=[int, float])

          거래금액   지역코드  건축년도     년   월   일   전용면적   층
0       215000  11680  1984  2021   1   1  95.40   9
1       178000  11680  1983  2021   1   1  53.06   3
2       181000  11680  1987  2021   1   3  78.93   3
3       157000  11680  1992  2021   1   4  60.00  13
4       150000  11680  1992  2021   1   4  49.86  12
...        ...    ...   ...   ...  ..  ..    ...  ..
233294   48900  11260  2004  2025  12   6  71.86   2
233295   49800  11260  2006  2025  12  14  69.60   5
233296   83000  11260  1997  2025  12  18  84.03   3
233297   72000  11260  1997  2025  12  26  59.76   9
233298   71000  11260  1997  2025  12  27  59.76  11

[233299 rows x 8 columns]

In [42]:
apt.columns

Index(['거래금액', '지역코드', '아파트', '시도명', '시군구', '법정동', '지번', '건축년도', '년', '월', '일',
       '등기일자', '매도자', '전용면적', '층'],
      dtype='object')

In [43]:
# str accessor(접근자) 문자열 또는 인덱스 원소열을 처리하는 함수를 포함하는 특수 객체 입니다.
apt.columns.str.contains(pat='년|월|일')

array([False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False])

In [45]:
apt.loc[:, apt.columns.str.contains(pat='년|월|일')]

        건축년도     년   월   일       등기일자
0       1984  2021   1   1        NaT
1       1983  2021   1   1        NaT
2       1987  2021   1   3        NaT
3       1992  2021   1   4        NaT
4       1992  2021   1   4        NaT
...      ...   ...  ..  ..        ...
233294  2004  2025  12   6 2026-02-27
233295  2006  2025  12  14 2026-01-20
233296  1997  2025  12  18 2026-02-27
233297  1997  2025  12  26 2026-03-30
233298  1997  2025  12  27 2026-02-12

[233299 rows x 5 columns]

In [47]:
nums = pd.Series(data=['M:010-234-6789', 'T:02-345-6789', 'ID:001231-7890123'])

In [49]:
nums.str[0:2]

0    M:
1    T:
2    ID
dtype: object

In [51]:
apt.select_dtypes(include='number')

          거래금액   지역코드  건축년도     년   월   일   전용면적   층
0       215000  11680  1984  2021   1   1  95.40   9
1       178000  11680  1983  2021   1   1  53.06   3
2       181000  11680  1987  2021   1   3  78.93   3
3       157000  11680  1992  2021   1   4  60.00  13
4       150000  11680  1992  2021   1   4  49.86  12
...        ...    ...   ...   ...  ..  ..    ...  ..
233294   48900  11260  2004  2025  12   6  71.86   2
233295   49800  11260  2006  2025  12  14  69.60   5
233296   83000  11260  1997  2025  12  18  84.03   3
233297   72000  11260  1997  2025  12  26  59.76   9
233298   71000  11260  1997  2025  12  27  59.76  11

[233299 rows x 8 columns]

In [52]:
nums.str.contains(pat='010')

0     True
1    False
2    False
dtype: bool

In [53]:
nums

0       M:010-234-6789
1        T:02-345-6789
2    ID:001231-7890123
dtype: object

In [54]:
nums.str.replace(pat='-', repl='')

0        M:0102346789
1         T:023456789
2    ID:0012317890123
dtype: object

In [55]:
nums

0       M:010-234-6789
1        T:02-345-6789
2    ID:001231-7890123
dtype: object

In [56]:
nums.str.extract(pat='([0-9]+)')

        0
0     010
1      02
2  001231

In [57]:
nums.str.extract(pat='(^[0-9]+)')

     0
0  NaN
1  NaN
2  NaN

In [58]:
nums.str.extract(pat='([0-9]+$)')

         0
0     6789
1     6789
2  7890123

In [59]:
cond = (apt['거래금액']<2000000)&(apt['층']>=65)
apt.loc[cond, :]

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
4632,458000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2021,6,24,NaT,NaN,214.967,66
5229,550000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2023,12,22,NaT,NaN,185.622,68
5577,550000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2024,7,30,2024-07-31,개인,185.622,68
5790,730000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2025,1,3,2025-02-28,개인,244.224,67
5936,620000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2025,3,8,2025-07-04,개인,163.944,67
185911,320000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2023,7,3,2023-10-17,NaN,167.440,65
186317,380000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2024,4,11,2024-06-20,개인,167.440,68
186844,300000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2024,10,14,2025-01-31,개인,138.200,67
187881,435000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2025,9,3,2025-12-22,개인,167.440,66

In [61]:
cond = apt['거래금액'].lt(2000000) & apt['층'].ge(65)
apt.loc[cond, :]

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
4632,458000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2021,6,24,NaT,NaN,214.967,66
5229,550000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2023,12,22,NaT,NaN,185.622,68
5577,550000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2024,7,30,2024-07-31,개인,185.622,68
5790,730000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2025,1,3,2025-02-28,개인,244.224,67
5936,620000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2025,3,8,2025-07-04,개인,163.944,67
185911,320000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2023,7,3,2023-10-17,NaN,167.440,65
186317,380000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2024,4,11,2024-06-20,개인,167.440,68
186844,300000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2024,10,14,2025-01-31,개인,138.200,67
187881,435000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2025,9,3,2025-12-22,개인,167.440,66

In [63]:
(apt['층'].ge(10) & apt['층'].le(20)).sum()

90953

In [65]:
apt['층'].between(10,20).sum()

90953

In [67]:
cond = apt['시군구'].eq('강남구')
apt.loc[cond, :].shape

(13546, 15)

In [68]:
cond1 = apt['시군구'].eq('강남구')
cond2 = apt['시군구'].eq('서초구')
cond3 = apt['시군구'].eq('송파구')
apt.loc[cond1|cond2|cond3, :]

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185033,174000,11710,현대1,서울특별시,송파구,풍납동,413-1,1995,2025,12,29,2026-03-20,개인,83.02,18
185034,125000,11710,신성노바빌아파트,서울특별시,송파구,풍납동,510,2000,2025,12,30,2026-03-31,개인,84.96,5
185035,100000,11710,강변현대,서울특별시,송파구,풍납동,299-1,1991,2025,12,31,2026-02-25,개인,83.19,3
185036,203000,11710,잠실올림픽공원아이파크,서울특별시,송파구,풍납동,514,2019,2025,12,31,2026-03-06,개인,59.97,13
185037,225000,11710,잠실올림픽공원아이파크,서울특별시,송파구,풍납동,514,2019,2025,12,31,2026-03-10,개인,84.99,7

In [70]:
cond = apt['시군구'].isin(['강남구', '서초구', '송파구'])
apt.loc[cond, :]

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185033,174000,11710,현대1,서울특별시,송파구,풍납동,413-1,1995,2025,12,29,2026-03-20,개인,83.02,18
185034,125000,11710,신성노바빌아파트,서울특별시,송파구,풍납동,510,2000,2025,12,30,2026-03-31,개인,84.96,5
185035,100000,11710,강변현대,서울특별시,송파구,풍납동,299-1,1991,2025,12,31,2026-02-25,개인,83.19,3
185036,203000,11710,잠실올림픽공원아이파크,서울특별시,송파구,풍납동,514,2019,2025,12,31,2026-03-06,개인,59.97,13
185037,225000,11710,잠실올림픽공원아이파크,서울특별시,송파구,풍납동,514,2019,2025,12,31,2026-03-10,개인,84.99,7

In [71]:
cond = apt['시군구'].str.contains(pat='^강')
apt.loc[cond, :].shape

(44350, 15)

In [73]:
apt.drop(columns=['지역코드'])

,거래금액,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,개인,71.86,2
233295,49800,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,개인,69.60,5
233296,83000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,개인,84.03,3
233297,72000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,개인,59.76,9
233298,71000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,개인,59.76,11

In [74]:
apt

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,11260,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,개인,71.86,2
233295,49800,11260,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,개인,69.60,5
233296,83000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,개인,84.03,3
233297,72000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,개인,59.76,9
233298,71000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,개인,59.76,11

In [75]:
apt.drop(columns=['지역코드', '매도자'], inplace=True)

In [76]:
apt

,거래금액,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,71.86,2
233295,49800,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,69.60,5
233296,83000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,84.03,3
233297,72000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,59.76,9
233298,71000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,59.76,11

In [77]:
apt.rename(columns={'아파트':'단지명', '건축년도':'입주년도'})

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,년,월,일,등기일자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,71.86,2
233295,49800,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,69.60,5
233296,83000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,84.03,3
233297,72000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,59.76,9
233298,71000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,59.76,11

In [78]:
apt.columns

Index(['거래금액', '아파트', '시도명', '시군구', '법정동', '지번', '건축년도', '년', '월', '일', '등기일자',
       '전용면적', '층'],
      dtype='object')

In [79]:
apt.columns = ['거래금액', '단지명', '시도명', '시군구', '법정동', '지번', '입주년도', '계약년', '계약월', '계약일', '등기일자',
       '전용면적', '층']

In [80]:
apt

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년,계약월,계약일,등기일자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,71.86,2
233295,49800,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,69.60,5
233296,83000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,84.03,3
233297,72000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,59.76,9
233298,71000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,59.76,11

In [81]:
apt['평당금액'] = apt['거래금액']/ apt['전용면적'] * 3.3
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년,계약월,계약일,등기일자,전용면적,층,평당금액
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.106918
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.486242
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.464842
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.000000
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.797834

In [82]:
apt['평당금액'].round(2)

0          7437.11
1         11070.49
2          7567.46
3          8635.00
4          9927.80
            ...
233294     2245.62
233295     2361.21
233296     3259.55
233297     3975.90
233298     3920.68
Name: 평당금액, Length: 233299, dtype: float64

In [83]:
# pd.set_option('display.float_format', lambda x: f'{x:.2f}')

In [84]:
apt['거래금액'] = apt['거래금액']/10000
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년,계약월,계약일,등기일자,전용면적,층,평당금액
0,21.5,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.106918
1,17.8,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.486242
2,18.1,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.464842
3,15.7,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.000000
4,15.0,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.797834

In [86]:
apt['경과년수'] = apt['계약년']- apt['입주년도']
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수
0,21.5,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.106918,37
1,17.8,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.486242,38
2,18.1,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.464842,34
3,15.7,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.000000,29
4,15.0,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.797834,29

In [88]:
apt.rename(columns = {'계약년':'계약년도'}, inplace=True)
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수
0,21.5,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.106918,37
1,17.8,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.486242,38
2,18.1,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.464842,34
3,15.7,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.000000,29
4,15.0,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.797834,29

In [89]:
cond = apt['경과년수'].ge(30)
apt['재건축'] = np.where(cond, '충족', '부족')
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수,재건축
0,21.5,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.106918,37,충족
1,17.8,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.486242,38,충족
2,18.1,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.464842,34,충족
3,15.7,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.000000,29,부족
4,15.0,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.797834,29,부족

In [90]:
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도             int64
계약월              int64
계약일              int64
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [91]:
apt['계약년도'] = apt['계약년도'].astype(str)
apt['계약월'] = apt['계약월'].astype(str)
apt['계약일'] = apt['계약일'].astype(str)

In [93]:
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도            object
계약월             object
계약일             object
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [94]:
apt = apt.astype({'계약년도':'int64', '계약월':'int64', '계약일':'int64'})
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도             int64
계약월              int64
계약일              int64
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [95]:
cols = ['계약년도', '계약월', '계약일']
apt[cols] = apt[cols].astype(str)
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도            object
계약월             object
계약일             object
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [99]:
apt['계약일자'] = apt['계약년도']+'-'+apt['계약월']+'-'+apt['계약일']
apt['계약일자'] = apt['계약일자'].astype('datetime64[ns]')

In [100]:
apt['계약일자'].dt.day_name()

0           Friday
1           Friday
2           Sunday
3           Monday
4           Monday
            ...
233294    Saturday
233295      Sunday
233296    Thursday
233297      Friday
233298    Saturday
Name: 계약일자, Length: 233299, dtype: object

In [105]:
apt['계약일자'].dt.day_name(locale='ko_KR').value_counts(normalize=True)*100

계약일자
토요일    24.946528
금요일    15.340400
수요일    14.153083
화요일    13.616003
월요일    13.401686
목요일    13.296671
일요일     5.245629
Name: proportion, dtype: float64

In [107]:
apt['계약일자'].dt.strftime('%a %b %d, %Y')

0         Fri Jan 01, 2021
1         Fri Jan 01, 2021
2         Sun Jan 03, 2021
3         Mon Jan 04, 2021
4         Mon Jan 04, 2021
                ...
233294    Sat Dec 06, 2025
233295    Sun Dec 14, 2025
233296    Thu Dec 18, 2025
233297    Fri Dec 26, 2025
233298    Sat Dec 27, 2025
Name: 계약일자, Length: 233299, dtype: object