In [1]:
'C:\Users\SDS\Documents\project\data'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3919027582.py, line 1)

In [2]:
'I am a boy'

'I am a boy'

In [4]:
"I'm a boy"

"I'm a boy"

In [5]:
'I\'m a boy'

"I'm a boy"

In [6]:
'C:\\Users\\SDS\\Documents\\project\\data'

'C:\\Users\\SDS\\Documents\\project\\data'

In [7]:
'C:/Users/SDS/Documents/project/data'

'C:/Users/SDS/Documents/project/data'

In [8]:
# raw string은 문자열 안의 이스케이프 기능을 일괄 해제
r'C:\Users\SDS\Documents\project\data'

'C:\\Users\\SDS\\Documents\\project\\data'

In [9]:
import os
import numpy as np
import pandas as pd

In [10]:
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [11]:
# 절대 경로 방식
os.chdir(path = 'C:\\Users\\SDS\\Documents\\project\\data')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [12]:
# 상대 경로 방식: '.'은 현재 폴더, '..'은 부모 폴더
os.chdir(path = '..')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project'

In [13]:
# [참고] './'는 생략 가능
os.chdir(path = './code')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [14]:
# [주의] '../'는 생략 불가능
os.chdir(path = '../data')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [15]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [16]:
[file for file in os.listdir() if 'iris' in file]

['iris.csv', 'iris.json', 'iris.parquet', 'iris.tsv', 'iris.xlsx']

In [17]:
[file for file in os.listdir() if '.csv' in file]

['APT_Price_Seoul_Merged_2021~2025.csv', 'iris.csv']

In [18]:
[file for file in os.listdir() if '2021' in file]

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx']

In [19]:
df1 = pd.read_excel('iris.xlsx')

In [23]:
# 함수 또는 객체의 메서드 괄호 안에 커서를 놓고 shift + tab 키를 동시에 누르면
# 해당 함수 또는 메서드의 설명서를 확인할 수 있습니다.
df1.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [27]:
df1.to_excel('test.xlsx', index = False)

In [28]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.xlsx']

In [29]:
df2 = pd.read_csv('iris.csv')
df2.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [30]:
df2.to_csv('test.csv', index = False)
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.csv',
 'test.xlsx']

In [32]:
# Python에서 텍스트 파일을 읽는 함수는 pd.read_csv() 하나로 충분!
df3 = pd.read_csv('iris.tsv', sep = '\t')
df3.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [33]:
df3.to_csv('test.tsv', index = False, sep = '\t')
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.csv',
 'test.tsv',
 'test.xlsx']

In [34]:
df4 = pd.read_json('iris.json')
df4.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [35]:
df4.to_json('test.json')
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.csv',
 'test.json',
 'test.tsv',
 'test.xlsx']

In [36]:
df5 = pd.read_parquet('iris.parquet')
df5.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [37]:
df5.to_parquet('test.parquet')
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx',
 'test.csv',
 'test.json',
 'test.parquet',
 'test.tsv',
 'test.xlsx']

In [38]:
files = [file for file in os.listdir() if 'test' in file]
files

['test.csv', 'test.json', 'test.parquet', 'test.tsv', 'test.xlsx']

In [39]:
for file in files:
    os.remove(file)

In [40]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']