In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [3]:
os.chdir('../data')

In [4]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [5]:
%time apt = pd.read_excel('APT_Price_Seoul_Merged_2021~2025.xlsx')

CPU times: total: 39 s
Wall time: 39.3 s

In [6]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [7]:
apt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233299 entries, 0 to 233298
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   거래금액    233299 non-null  int64
 1   지역코드    233299 non-null  int64
 2   아파트     233299 non-null  object
 3   시도명     233299 non-null  object
 4   시군구     233299 non-null  object
 5   법정동     233299 non-null  object
 6   지번      233299 non-null  object
 7   건축년도    233299 non-null  int64
 8   년       233299 non-null  int64
 9   월       233299 non-null  int64
 10  일       233299 non-null  int64
 11  등기일자    165337 non-null  datetime64[ns]
 12  매도자     141486 non-null  object
 13  전용면적    233299 non-null  float64
 14  층       233299 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.7+ MB

In [12]:
# 날짜시간형으로 읽으려면 원소가 'yyyy-mm-dd' 형태이어야 합니다.
%time apt = pd.read_csv('APT_Price_Seoul_Merged_2021~2025.csv', parse_dates = ['등기일자'])

CPU times: total: 422 ms
Wall time: 439 ms

In [13]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [14]:
apt.tail()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
233294,48900,11260,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,개인,71.86,2
233295,49800,11260,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,개인,69.60,5
233296,83000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,개인,84.03,3
233297,72000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,개인,59.76,9
233298,71000,11260,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,개인,59.76,11

In [15]:
apt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233299 entries, 0 to 233298
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   거래금액    233299 non-null  int64
 1   지역코드    233299 non-null  int64
 2   아파트     233299 non-null  object
 3   시도명     233299 non-null  object
 4   시군구     233299 non-null  object
 5   법정동     233299 non-null  object
 6   지번      233299 non-null  object
 7   건축년도    233299 non-null  int64
 8   년       233299 non-null  int64
 9   월       233299 non-null  int64
 10  일       233299 non-null  int64
 11  등기일자    165337 non-null  datetime64[ns]
 12  매도자     141486 non-null  object
 13  전용면적    233299 non-null  float64
 14  층       233299 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.7+ MB

In [17]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [16]:
apt['지역코드']

0         11680
1         11680
2         11680
3         11680
4         11680
          ...
233294    11260
233295    11260
233296    11260
233297    11260
233298    11260
Name: 지역코드, Length: 233299, dtype: int64

In [19]:
apt.loc[:, '지역코드']

0         11680
1         11680
2         11680
3         11680
4         11680
          ...
233294    11260
233295    11260
233296    11260
233297    11260
233298    11260
Name: 지역코드, Length: 233299, dtype: int64

In [20]:
apt.iloc[:, 1]

0         11680
1         11680
2         11680
3         11680
4         11680
          ...
233294    11260
233295    11260
233296    11260
233297    11260
233298    11260
Name: 지역코드, Length: 233299, dtype: int64

In [21]:
apt[['지역코드', '거래금액']]

         지역코드    거래금액
0       11680  215000
1       11680  178000
2       11680  181000
3       11680  157000
4       11680  150000
...       ...     ...
233294  11260   48900
233295  11260   49800
233296  11260   83000
233297  11260   72000
233298  11260   71000

[233299 rows x 2 columns]

In [22]:
apt[['거래금액', '지역코드']]

          거래금액   지역코드
0       215000  11680
1       178000  11680
2       181000  11680
3       157000  11680
4       150000  11680
...        ...    ...
233294   48900  11260
233295   49800  11260
233296   83000  11260
233297   72000  11260
233298   71000  11260

[233299 rows x 2 columns]

In [23]:
apt.loc[:, ['지역코드', '거래금액']]

         지역코드    거래금액
0       11680  215000
1       11680  178000
2       11680  181000
3       11680  157000
4       11680  150000
...       ...     ...
233294  11260   48900
233295  11260   49800
233296  11260   83000
233297  11260   72000
233298  11260   71000

[233299 rows x 2 columns]

In [24]:
apt.iloc[:, [1, 0]]

         지역코드    거래금액
0       11680  215000
1       11680  178000
2       11680  181000
3       11680  157000
4       11680  150000
...       ...     ...
233294  11260   48900
233295  11260   49800
233296  11260   83000
233297  11260   72000
233298  11260   71000

[233299 rows x 2 columns]

In [25]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [28]:
# apt[['거래금액', '지역코드', '아파트']]
# apt['거래금액':'아파트']
apt.loc[:, '거래금액':'아파트']

          거래금액   지역코드                    아파트
0       215000  11680          현대1차101동~106동
1       178000  11680                개포주공6단지
2       181000  11680                    우성8
3       157000  11680                삼익대청아파트
4       150000  11680             성원대치2단지아파트
...        ...    ...                    ...
233294   48900  11260                 강오(B동)
233295   49800  11260                     태솔
233296   83000  11260  한신아파트상가동유치원동(103~109)
233297   72000  11260  한신아파트상가동유치원동(103~109)
233298   71000  11260  한신아파트상가동유치원동(103~109)

[233299 rows x 3 columns]

In [29]:
apt.dtypes

거래금액             int64
지역코드             int64
아파트             object
시도명             object
시군구             object
법정동             object
지번              object
건축년도             int64
년                int64
월                int64
일                int64
등기일자    datetime64[ns]
매도자             object
전용면적           float64
층                int64
dtype: object

In [30]:
apt.dtypes == 'int64'

거래금액     True
지역코드     True
아파트     False
시도명     False
시군구     False
법정동     False
지번      False
건축년도     True
년        True
월        True
일        True
등기일자    False
매도자     False
전용면적    False
층        True
dtype: bool

In [31]:
apt.loc[:, apt.dtypes == 'int64']

          거래금액   지역코드  건축년도     년   월   일   층
0       215000  11680  1984  2021   1   1   9
1       178000  11680  1983  2021   1   1   3
2       181000  11680  1987  2021   1   3   3
3       157000  11680  1992  2021   1   4  13
4       150000  11680  1992  2021   1   4  12
...        ...    ...   ...   ...  ..  ..  ..
233294   48900  11260  2004  2025  12   6   2
233295   49800  11260  2006  2025  12  14   5
233296   83000  11260  1997  2025  12  18   3
233297   72000  11260  1997  2025  12  26   9
233298   71000  11260  1997  2025  12  27  11

[233299 rows x 7 columns]

In [32]:
apt.loc[:, apt.dtypes == 'float64']

         전용면적
0       95.40
1       53.06
2       78.93
3       60.00
4       49.86
...       ...
233294  71.86
233295  69.60
233296  84.03
233297  59.76
233298  59.76

[233299 rows x 1 columns]

In [34]:
apt.loc[:, (apt.dtypes == 'int64') | (apt.dtypes == 'float64')]

          거래금액   지역코드  건축년도     년   월   일   전용면적   층
0       215000  11680  1984  2021   1   1  95.40   9
1       178000  11680  1983  2021   1   1  53.06   3
2       181000  11680  1987  2021   1   3  78.93   3
3       157000  11680  1992  2021   1   4  60.00  13
4       150000  11680  1992  2021   1   4  49.86  12
...        ...    ...   ...   ...  ..  ..    ...  ..
233294   48900  11260  2004  2025  12   6  71.86   2
233295   49800  11260  2006  2025  12  14  69.60   5
233296   83000  11260  1997  2025  12  18  84.03   3
233297   72000  11260  1997  2025  12  26  59.76   9
233298   71000  11260  1997  2025  12  27  59.76  11

[233299 rows x 8 columns]

In [35]:
apt.select_dtypes(include = [int, float])

          거래금액   지역코드  건축년도     년   월   일   전용면적   층
0       215000  11680  1984  2021   1   1  95.40   9
1       178000  11680  1983  2021   1   1  53.06   3
2       181000  11680  1987  2021   1   3  78.93   3
3       157000  11680  1992  2021   1   4  60.00  13
4       150000  11680  1992  2021   1   4  49.86  12
...        ...    ...   ...   ...  ..  ..    ...  ..
233294   48900  11260  2004  2025  12   6  71.86   2
233295   49800  11260  2006  2025  12  14  69.60   5
233296   83000  11260  1997  2025  12  18  84.03   3
233297   72000  11260  1997  2025  12  26  59.76   9
233298   71000  11260  1997  2025  12  27  59.76  11

[233299 rows x 8 columns]

In [36]:
apt.columns

Index(['거래금액', '지역코드', '아파트', '시도명', '시군구', '법정동', '지번', '건축년도', '년', '월', '일',
       '등기일자', '매도자', '전용면적', '층'],
      dtype='object')

In [37]:
# str accessor(접근자) 문자열 또는 인덱스 원소별로 문자열을 처리하는 함수를 포함하는 특수 객체입니다.
apt.columns.str.contains(pat = '년|월|일')

array([False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False])

In [39]:
apt.loc[:, apt.columns.str.contains(pat = '년|월|일')]

        건축년도     년   월   일       등기일자
0       1984  2021   1   1        NaT
1       1983  2021   1   1        NaT
2       1987  2021   1   3        NaT
3       1992  2021   1   4        NaT
4       1992  2021   1   4        NaT
...      ...   ...  ..  ..        ...
233294  2004  2025  12   6 2026-02-27
233295  2006  2025  12  14 2026-01-20
233296  1997  2025  12  18 2026-02-27
233297  1997  2025  12  26 2026-03-30
233298  1997  2025  12  27 2026-02-12

[233299 rows x 5 columns]

In [40]:
nums = pd.Series(data = ['M:010-2345-6789', 'T:02-345-6789', 'ID:001231-7890123'])

In [41]:
nums.str[0:2]

0    M:
1    T:
2    ID
dtype: object

In [42]:
nums.str.split(':|-')

0     [M, 010, 2345, 6789]
1       [T, 02, 345, 6789]
2    [ID, 001231, 7890123]
dtype: object

In [43]:
nums.str.split(':|-').str[0]

0     M
1     T
2    ID
dtype: object

In [44]:
nums.str.contains(pat = '010')

0     True
1    False
2    False
dtype: bool

In [45]:
nums.str.replace(pat = '-', repl = '')

0       M:01023456789
1         T:023456789
2    ID:0012317890123
dtype: object

In [50]:
nums

0      M:010-2345-6789
1        T:02-345-6789
2    ID:001231-7890123
dtype: object

In [47]:
nums.str.extract(pat = '([0-9]+)')

        0
0     010
1      02
2  001231

In [52]:
# method chaining: nums라는 시리즈에 문자열 변경을 실행한 결과도 시리즈이므로, 
# 이어서 str 접근자를 추가 실행할 수 있습니다.
nums.str.replace(pat = '-', repl = '').str.extract(pat = '([0-9]+)')

               0
0    01023456789
1      023456789
2  0012317890123

In [48]:
nums.str.extract(pat = '(^[0-9]+)')

     0
0  NaN
1  NaN
2  NaN

In [49]:
nums.str.extract(pat = '([0-9]+$)')

         0
0     6789
1     6789
2  7890123

In [53]:
cond = (apt['거래금액'] >= 2_000_000)
cond

0         False
1         False
2         False
3         False
4         False
          ...
233294    False
233295    False
233296    False
233297    False
233298    False
Name: 거래금액, Length: 233299, dtype: bool

In [54]:
apt.loc[cond, :]

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
150126,2900000,11200,아크로서울포레스트,서울특별시,성동구,성수동1가,685-700,2020,2025,6,11,2025-12-19,개인,273.9280,47
211129,2000000,11170,나인원한남,서울특별시,용산구,한남동,829,2019,2024,6,4,2024-07-15,개인,273.9424,1
211152,2200000,11170,나인원한남,서울특별시,용산구,한남동,829,2019,2024,7,22,2025-07-22,개인,273.4125,1
211159,2500000,11170,나인원한남,서울특별시,용산구,한남동,829,2019,2024,8,13,2025-07-01,개인,273.9424,1
211204,2500000,11170,나인원한남,서울특별시,용산구,한남동,829,2019,2025,2,10,2025-05-28,개인,273.9424,1

In [55]:
cond = (apt['거래금액'] < 2_000_000) & (apt['층'] >= 65)

In [56]:
apt.loc[cond, :]

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
4632,458000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2021,6,24,NaT,NaN,214.967,66
5229,550000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2023,12,22,NaT,NaN,185.622,68
5577,550000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2024,7,30,2024-07-31,개인,185.622,68
5790,730000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2025,1,3,2025-02-28,개인,244.224,67
5936,620000,11680,타워팰리스3,서울특별시,강남구,도곡동,467-29,2004,2025,3,8,2025-07-04,개인,163.944,67
185911,320000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2023,7,3,2023-10-17,NaN,167.440,65
186317,380000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2024,4,11,2024-06-20,개인,167.440,68
186844,300000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2024,10,14,2025-01-31,개인,138.200,67
187881,435000,11470,현대하이페리온,서울특별시,양천구,목동,916,2003,2025,9,3,2025-12-22,개인,167.440,66

In [57]:
cond = apt['거래금액'].lt(2_000_000) & apt['층'].ge(65)
cond.sum()

9

In [60]:
(apt['층'].ge(10) & apt['층'].le(20)).sum()

90953

In [61]:
apt['층'].between(10, 20).sum()

90953

In [63]:
cond = apt['시군구'].eq('강남구')
apt.loc[cond, :].shape

(13546, 15)

In [64]:
cond1 = apt['시군구'].eq('강남구')
cond2 = apt['시군구'].eq('서초구')
cond3 = apt['시군구'].eq('송파구')
apt.loc[cond1 | cond2 | cond3, :].shape

(39869, 15)

In [65]:
cond = apt['시군구'].isin(['강남구', '서초구', '송파구'])
apt.loc[cond, :].shape

(39869, 15)

In [67]:
cond = apt['시군구'].isin(['강남구', '강동구', '강서구', '강북구'])
apt.loc[cond, :].shape

(44350, 15)

In [68]:
cond = apt['시군구'].str.contains(pat = '^강')
apt.loc[cond, :].shape

(44350, 15)

In [69]:
apt.drop(columns = '지역코드')

,거래금액,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,개인,71.86,2
233295,49800,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,개인,69.60,5
233296,83000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,개인,84.03,3
233297,72000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,개인,59.76,9
233298,71000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,개인,59.76,11

In [70]:
apt.head()

,거래금액,지역코드,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,매도자,전용면적,층
0,215000,11680,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,NaN,95.40,9
1,178000,11680,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,NaN,53.06,3
2,181000,11680,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,NaN,78.93,3
3,157000,11680,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,60.00,13
4,150000,11680,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,NaN,49.86,12

In [71]:
apt = apt.drop(columns = ['지역코드', '매도자'])

In [72]:
apt.head()

,거래금액,아파트,시도명,시군구,법정동,지번,건축년도,년,월,일,등기일자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12

In [73]:
apt.rename(columns = {'아파트': '단지명', '건축년도': '입주년도'})

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,년,월,일,등기일자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,48900,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,71.86,2
233295,49800,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,69.60,5
233296,83000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,84.03,3
233297,72000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,59.76,9
233298,71000,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,59.76,11

In [74]:
apt.columns

Index(['거래금액', '아파트', '시도명', '시군구', '법정동', '지번', '건축년도', '년', '월', '일', '등기일자',
       '전용면적', '층'],
      dtype='object')

In [75]:
# 데이터프레임의 열 개수와 오른쪽 열이름 리스트 개수가 동일해야만 정상적으로 실행됩니다.
apt.columns = ['거래금액', '단지명', '시도명', '시군구', '법정동', '지번', 
               '입주년도', '계약년도', '계약월', '계약일', '등기일자',
               '전용면적', '층']

In [76]:
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12

In [77]:
apt['평당금액'] = apt['거래금액'] / apt['전용면적'] * 3.3
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.106918
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.486242
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.464842
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.000000
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.797834

In [78]:
apt['평당금액'].round(2)

0          7437.11
1         11070.49
2          7567.46
3          8635.00
4          9927.80
            ...
233294     2245.62
233295     2361.21
233296     3259.55
233297     3975.90
233298     3920.68
Name: 평당금액, Length: 233299, dtype: float64

In [79]:
pd.set_option('display.float_format', lambda x: f'{x:.2f}')

In [80]:
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액
0,215000,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.11
1,178000,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.49
2,181000,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.46
3,157000,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.00
4,150000,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.80

In [81]:
apt['거래금액'] = apt['거래금액'] / 10_000
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액
0,21.50,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.11
1,17.80,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.49
2,18.10,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.46
3,15.70,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.00
4,15.00,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.80

In [82]:
apt['경과년수'] = apt['계약년도'] - apt['입주년도']
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수
0,21.50,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.11,37
1,17.80,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.49,38
2,18.10,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.46,34
3,15.70,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.00,29
4,15.00,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.80,29

In [83]:
cond = apt['경과년수'].ge(30)
apt['재건축'] = np.where(cond, '충족', '부족')
apt.head()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수,재건축
0,21.50,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,NaT,95.40,9,7437.11,37,충족
1,17.80,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,NaT,53.06,3,11070.49,38,충족
2,18.10,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,NaT,78.93,3,7567.46,34,충족
3,15.70,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,60.00,13,8635.00,29,부족
4,15.00,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,NaT,49.86,12,9927.80,29,부족

In [84]:
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도             int64
계약월              int64
계약일              int64
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [85]:
apt['계약년도'] = apt['계약년도'].astype(str)
apt['계약월'] = apt['계약월'].astype(str)
apt['계약일'] = apt['계약일'].astype(str)

In [86]:
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도            object
계약월             object
계약일             object
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [89]:
apt = apt.astype({'계약년도': 'int64', '계약월': 'int64', '계약일': 'int64'})

In [90]:
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도             int64
계약월              int64
계약일              int64
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [92]:
cols = ['계약년도', '계약월', '계약일']
apt[cols] = apt[cols].astype(str)
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도            object
계약월             object
계약일             object
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
dtype: object

In [93]:
'2026' + '-' + '05' + '-' + '12'

'2026-05-12'

In [95]:
apt['계약일자'] = apt['계약년도'] + '-' + apt['계약월'] + '-' + apt['계약일']

In [97]:
apt['계약일자'] = apt['계약일자'].astype('datetime64[ns]')

In [98]:
apt.dtypes

거래금액           float64
단지명             object
시도명             object
시군구             object
법정동             object
지번              object
입주년도             int64
계약년도            object
계약월             object
계약일             object
등기일자    datetime64[ns]
전용면적           float64
층                int64
평당금액           float64
경과년수             int64
재건축             object
계약일자    datetime64[ns]
dtype: object

In [99]:
apt['계약일자'].dt.dayofweek

0         4
1         4
2         6
3         0
4         0
         ..
233294    5
233295    6
233296    3
233297    4
233298    5
Name: 계약일자, Length: 233299, dtype: int32

In [100]:
apt['계약일자'].dt.day_name()

0           Friday
1           Friday
2           Sunday
3           Monday
4           Monday
            ...
233294    Saturday
233295      Sunday
233296    Thursday
233297      Friday
233298    Saturday
Name: 계약일자, Length: 233299, dtype: object

In [101]:
apt['계약일자'].dt.day_name(locale = 'ko_KR')

0         금요일
1         금요일
2         일요일
3         월요일
4         월요일
         ...
233294    토요일
233295    일요일
233296    목요일
233297    금요일
233298    토요일
Name: 계약일자, Length: 233299, dtype: object

In [102]:
apt['계약일자'].dt.day_name(locale = 'ko_KR').value_counts()

계약일자
토요일    58200
금요일    35789
수요일    33019
화요일    31766
월요일    31266
목요일    31021
일요일    12238
Name: count, dtype: int64

In [104]:
apt['계약일자'].dt.day_name(locale = 'ko_KR').value_counts(normalize = True) * 100

계약일자
토요일   24.95
금요일   15.34
수요일   14.15
화요일   13.62
월요일   13.40
목요일   13.30
일요일    5.25
Name: proportion, dtype: float64

In [105]:
apt['계약일자'].dt.strftime('%Y년 %m월 %d일')

0         2021년 01월 01일
1         2021년 01월 01일
2         2021년 01월 03일
3         2021년 01월 04일
4         2021년 01월 04일
              ...
233294    2025년 12월 06일
233295    2025년 12월 14일
233296    2025년 12월 18일
233297    2025년 12월 26일
233298    2025년 12월 27일
Name: 계약일자, Length: 233299, dtype: object

In [108]:
apt['계약일자'].dt.strftime('%a %b %d, %Y')

0         Fri Jan 01, 2021
1         Fri Jan 01, 2021
2         Sun Jan 03, 2021
3         Mon Jan 04, 2021
4         Mon Jan 04, 2021
                ...
233294    Sat Dec 06, 2025
233295    Sun Dec 14, 2025
233296    Thu Dec 18, 2025
233297    Fri Dec 26, 2025
233298    Sat Dec 27, 2025
Name: 계약일자, Length: 233299, dtype: object

In [109]:
apt['처리일수'] = apt['등기일자'] - apt['계약일자']

In [110]:
apt['처리일수']

0            NaT
1            NaT
2            NaT
3            NaT
4            NaT
           ...
233294   83 days
233295   37 days
233296   71 days
233297   94 days
233298   47 days
Name: 처리일수, Length: 233299, dtype: timedelta64[ns]

In [112]:
apt['처리일수'].dt.days.mean()

82.92169931715225

In [114]:
# pd.Series(data = ['2000년 1월 1일']).astype('datetime64[ns]')
birth = pd.to_datetime(arg = '2000년 1월 1일', format = '%Y년 %m월 %d일')
birth

Timestamp('2000-01-01 00:00:00')

In [115]:
birth.timestamp()

946684800.0

In [116]:
today = pd.Timestamp.today()
today

Timestamp('2026-05-12 14:33:06.198182')

In [117]:
today.timestamp()

1778596386.198182

In [119]:
dtGap = today - birth

In [122]:
dtGap.days * 3 * 8000

231072000

In [123]:
apt['단지명']

0                 현대1차101동~106동
1                       개포주공6단지
2                           우성8
3                       삼익대청아파트
4                    성원대치2단지아파트
                  ...
233294                   강오(B동)
233295                       태솔
233296    한신아파트상가동유치원동(103~109)
233297    한신아파트상가동유치원동(103~109)
233298    한신아파트상가동유치원동(103~109)
Name: 단지명, Length: 233299, dtype: object

In [124]:
apt['단지명'].apply(func = len)

0         13
1          7
2          3
3          7
4         10
          ..
233294     6
233295     2
233296    21
233297    21
233298    21
Name: 단지명, Length: 233299, dtype: int64

In [125]:
cols = ['시도명', '시군구', '법정동', '지번']
apt[cols]

          시도명  시군구  법정동      지번
0       서울특별시  강남구  개포동     653
1       서울특별시  강남구  개포동     185
2       서울특별시  강남구  개포동     179
3       서울특별시  강남구  개포동      12
4       서울특별시  강남구  개포동      12
...       ...  ...  ...     ...
233294  서울특별시  중랑구  중화동   307-6
233295  서울특별시  중랑구  중화동  318-81
233296  서울특별시  중랑구  중화동     450
233297  서울특별시  중랑구  중화동     450
233298  서울특별시  중랑구  중화동     450

[233299 rows x 4 columns]

In [126]:
apt[cols].apply(func = len, axis = 0)

시도명    233299
시군구    233299
법정동    233299
지번     233299
dtype: int64

In [127]:
apt[cols].apply(func = len, axis = 1)

0         4
1         4
2         4
3         4
4         4
         ..
233294    4
233295    4
233296    4
233297    4
233298    4
Length: 233299, dtype: int64

In [162]:
apt[cols].map(func = len)

        시도명  시군구  법정동  지번
0         5    3    3   3
1         5    3    3   3
2         5    3    3   3
3         5    3    3   2
4         5    3    3   2
...     ...  ...  ...  ..
233294    5    3    3   5
233295    5    3    3   6
233296    5    3    3   3
233297    5    3    3   3
233298    5    3    3   3

[233299 rows x 4 columns]

In [128]:
addr = ['서울특별시', '강남구', '압구정동', '1']
' '.join(addr)

'서울특별시 강남구 압구정동 1'

In [131]:
apt['시도명'] + ' ' + apt['시군구'] + ' ' + apt['법정동']  + ' ' + apt['지번']

0            서울특별시 강남구 개포동 653
1            서울특별시 강남구 개포동 185
2            서울특별시 강남구 개포동 179
3             서울특별시 강남구 개포동 12
4             서울특별시 강남구 개포동 12
                  ...
233294     서울특별시 중랑구 중화동 307-6
233295    서울특별시 중랑구 중화동 318-81
233296       서울특별시 중랑구 중화동 450
233297       서울특별시 중랑구 중화동 450
233298       서울특별시 중랑구 중화동 450
Length: 233299, dtype: object

In [129]:
str_join = lambda x: ' '.join(x)

In [130]:
apt[cols].apply(func = str_join, axis = 1)

0            서울특별시 강남구 개포동 653
1            서울특별시 강남구 개포동 185
2            서울특별시 강남구 개포동 179
3             서울특별시 강남구 개포동 12
4             서울특별시 강남구 개포동 12
                  ...
233294     서울특별시 중랑구 중화동 307-6
233295    서울특별시 중랑구 중화동 318-81
233296       서울특별시 중랑구 중화동 450
233297       서울특별시 중랑구 중화동 450
233298       서울특별시 중랑구 중화동 450
Length: 233299, dtype: object

In [132]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [133]:
df = pd.read_excel('iris.xlsx')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0          5.10         3.50          1.40         0.20  setosa
1          4.90         3.00          1.40         0.20  setosa
2          4.70         3.20          1.30         0.20  setosa
3          4.60         3.10          1.50         0.20  setosa
4          5.00         3.60          1.40         0.20  setosa

In [134]:
X = df.loc[:, 'sepal_length':'petal_length']
X.head()

   sepal_length  sepal_width  petal_length
0          5.10         3.50          1.40
1          4.90         3.00          1.40
2          4.70         3.20          1.30
3          4.60         3.10          1.50
4          5.00         3.60          1.40

In [135]:
y = df['petal_width']

In [136]:
from scipy import stats

In [141]:
stats.pearsonr(x = X['sepal_length'], y = y)[1]

2.3254980797931624e-37

In [144]:
corr = lambda x: stats.pearsonr(x = x, y = y)[0]

In [146]:
X.apply(func = corr, axis = 0).ge(0.5)

sepal_length     True
sepal_width     False
petal_length     True
dtype: bool

In [147]:
apt.isna()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수,재건축,계약일자,처리일수
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
233295,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
233296,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
233297,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
233298,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [149]:
apt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233299 entries, 0 to 233298
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   거래금액    233299 non-null  float64
 1   단지명     233299 non-null  object
 2   시도명     233299 non-null  object
 3   시군구     233299 non-null  object
 4   법정동     233299 non-null  object
 5   지번      233299 non-null  object
 6   입주년도    233299 non-null  int64
 7   계약년도    233299 non-null  object
 8   계약월     233299 non-null  object
 9   계약일     233299 non-null  object
 10  등기일자    165337 non-null  datetime64[ns]
 11  전용면적    233299 non-null  float64
 12  층       233299 non-null  int64
 13  평당금액    233299 non-null  float64
 14  경과년수    233299 non-null  int64
 15  재건축     233299 non-null  object
 16  계약일자    233299 non-null  datetime64[ns]
 17  처리일수    165337 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(3), int64(3), object(9), timedelta64[ns](1)
memory usage: 32.0+ MB

In [148]:
apt.isna().sum()

거래금액        0
단지명         0
시도명         0
시군구         0
법정동         0
지번          0
입주년도        0
계약년도        0
계약월         0
계약일         0
등기일자    67962
전용면적        0
층           0
평당금액        0
경과년수        0
재건축         0
계약일자        0
처리일수    67962
dtype: int64

In [151]:
apt.isna().mean() * 100

거래금액    0.00
단지명     0.00
시도명     0.00
시군구     0.00
법정동     0.00
지번      0.00
입주년도    0.00
계약년도    0.00
계약월     0.00
계약일     0.00
등기일자   29.13
전용면적    0.00
층       0.00
평당금액    0.00
경과년수    0.00
재건축     0.00
계약일자    0.00
처리일수   29.13
dtype: float64

In [154]:
apt['등기일자'].fillna('1900-01-01')

0        1900-01-01
1        1900-01-01
2        1900-01-01
3        1900-01-01
4        1900-01-01
            ...
233294   2026-02-27
233295   2026-01-20
233296   2026-02-27
233297   2026-03-30
233298   2026-02-12
Name: 등기일자, Length: 233299, dtype: datetime64[ns]

In [155]:
days_avg = apt['처리일수'].dt.days.mean()
days_avg

82.92169931715225

In [157]:
apt['등기일자'].fillna(apt['계약일자'] + pd.Timedelta(days = days_avg))

0        2021-03-24 22:07:14.821001954
1        2021-03-24 22:07:14.821001954
2        2021-03-26 22:07:14.821001954
3        2021-03-27 22:07:14.821001954
4        2021-03-27 22:07:14.821001954
                      ...
233294   2026-02-27 00:00:00.000000000
233295   2026-01-20 00:00:00.000000000
233296   2026-02-27 00:00:00.000000000
233297   2026-03-30 00:00:00.000000000
233298   2026-02-12 00:00:00.000000000
Name: 등기일자, Length: 233299, dtype: datetime64[ns]

In [158]:
apt.dropna()

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,등기일자,전용면적,층,평당금액,경과년수,재건축,계약일자,처리일수
325,29.00,경남1,서울특별시,강남구,개포동,649,1984,2023,1,2,2023-04-10,166.48,8,5748.44,39,충족,2023-01-02,98 days
326,8.17,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2023,1,2,2023-03-30,33.18,2,8125.68,31,충족,2023-01-02,87 days
327,12.90,래미안블레스티지,서울특별시,강남구,개포동,1280,2019,2023,1,2,2023-01-12,49.91,10,8529.52,4,부족,2023-01-02,10 days
328,21.00,개포주공5단지,서울특별시,강남구,개포동,187,1983,2023,1,3,2023-03-30,74.25,10,9333.33,40,충족,2023-01-03,86 days
329,8.30,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2023,1,3,2023-03-28,33.18,14,8254.97,31,충족,2023-01-03,84 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,4.89,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,2026-02-27,71.86,2,2245.62,21,부족,2025-12-06,83 days
233295,4.98,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,2026-01-20,69.60,5,2361.21,19,부족,2025-12-14,37 days
233296,8.30,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,2026-02-27,84.03,3,3259.55,28,부족,2025-12-18,71 days
233297,7.20,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,2026-03-30,59.76,9,3975.90,28,부족,2025-12-26,94 days
233298,7.10,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,2026-02-12,59.76,11,3920.68,28,부족,2025-12-27,47 days

In [159]:
apt.dropna(axis = 1)

,거래금액,단지명,시도명,시군구,법정동,지번,입주년도,계약년도,계약월,계약일,전용면적,층,평당금액,경과년수,재건축,계약일자
0,21.50,현대1차101동~106동,서울특별시,강남구,개포동,653,1984,2021,1,1,95.40,9,7437.11,37,충족,2021-01-01
1,17.80,개포주공6단지,서울특별시,강남구,개포동,185,1983,2021,1,1,53.06,3,11070.49,38,충족,2021-01-01
2,18.10,우성8,서울특별시,강남구,개포동,179,1987,2021,1,3,78.93,3,7567.46,34,충족,2021-01-03
3,15.70,삼익대청아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,60.00,13,8635.00,29,부족,2021-01-04
4,15.00,성원대치2단지아파트,서울특별시,강남구,개포동,12,1992,2021,1,4,49.86,12,9927.80,29,부족,2021-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233294,4.89,강오(B동),서울특별시,중랑구,중화동,307-6,2004,2025,12,6,71.86,2,2245.62,21,부족,2025-12-06
233295,4.98,태솔,서울특별시,중랑구,중화동,318-81,2006,2025,12,14,69.60,5,2361.21,19,부족,2025-12-14
233296,8.30,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,18,84.03,3,3259.55,28,부족,2025-12-18
233297,7.20,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,26,59.76,9,3975.90,28,부족,2025-12-26
233298,7.10,한신아파트상가동유치원동(103~109),서울특별시,중랑구,중화동,450,1997,2025,12,27,59.76,11,3920.68,28,부족,2025-12-27

In [160]:
apt = apt.dropna(axis = 1)
apt.shape

(233299, 16)