In [1]:
import ko_spelling_et5

저장된 모델을 불러옵니다...

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

모델 로딩을 완료했습니다!

In [2]:
import os, pandas as pd, numpy as np

In [3]:
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\code'

In [4]:
os.chdir('../data')
os.getcwd()

'C:\\Users\\SDS\\Documents\\project\\data'

In [5]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [6]:
df = pd.read_excel('Galaxy_Book_Review_20250131.xlsx')
df.head()

        date  star  like                                               text
0 2025-01-13     5     3  빠르게 배송해주셔서 감사합니다.여기서 항상 사무용 노트북 주문하고 있네요.한가지 아...
1 2025-01-25     5     2  지난번에 구입하고 일주일 간격으로 재구매.좋아요. 사장님 사은품 없습니꽈?  사이즈...
2 2025-01-14     5     2  메모리 잘 추가되어 도착했고, 윈도우 설치할때 ms 계정때문에 잠깐 어려웠는데 인터...
3 2025-01-23     4     2  자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요. 배터리는 좀 빨리 ...
4 2025-01-25     5     2               가격도 맘에들고 다 좋아요!! 엄마가 쓰려고 구매했는데 만족하셔요

In [ ]:
pt = '[^가-힣A-Za-z0-9]+'

df['text'] = df['text'].str.replace(pat = pt, repl=" ", regex=True).str.upper()
df['text'].head()

In [13]:
corrected = ko_spelling_et5.correct('복리후생으로워라벨부터챙기잨ㅋㅋㅋ')

In [14]:
corrected

'복리후생으로 워라벨부터 챙기자 ᄏᄏᄏᄏ.'

In [15]:
texts = ['지인짜 ㄱ암사하빈다', '빠를 배송조아여', '증말 마시따', '고나리자에게 문의']

In [16]:
ko_spelling_et5.correct(texts)

  0%|          | 0/4 [00:00<?, ?it/s]

['진짜 암사합니다.', '빠를 배송 좋아요.', '정말 맛있어.', '고나리에게 문의.']

In [17]:
ko_spelling_et5.correct(df['text'].head(10))

  0%|          | 0/10 [00:00<?, ?it/s]

0    빠르게 배송해 주셔서 감사합니다 여기서 항상 사무용 노트북 주문하고 있네요 한 가지...
1    지난번에 구입하고 일주일 간격으로 재구매 좋아요 사장님 사은품 없습니까? 사이즈도 ...
2    메모리 잘 추가되어 도착했고 윈도우 설치할 때 MS 계정 때문에 잠깐 어려웠는데 인...
3    자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요 배터리는 좀 빨리 닳...
4                 가격도 맘에 들고 다 좋아요 엄마가 쓰려고 구매했는데 만족하셔요.
5    우선 디자인이 좋아요 폼 나요 저는 오래 쓰려고 옵션 빵빵하게 채웠더니 한 10년 ...
6    좋네요 직접 윈도우 설치하고 등등 아이가 대만족합니다 조만간 봐서 1 2대 더 구입...
7                                재구매했어요 사무용으로 나쁘지 않아요.
8                                     가성비로 괜찮네요 감사합니다.
9    포장이 아주 튼튼하네요 잘 받았고 소프트웨어 관련 WINDOW11은 옵션으로 되어 ...
dtype: object

In [18]:
df['text']

0        빠르게 배송해주셔서 감사합니다 여기서 항상 사무용 노트북 주문하고 있네요 한가지 아...
1        지난번에 구입하고 일주일 간격으로 재구매 좋아요 사장님 사은품 없습니꽈 사이즈도 성...
2        메모리 잘 추가되어 도착했고 윈도우 설치할때 MS 계정때문에 잠깐 어려웠는데 인터넷...
3        자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요 배터리는 좀 빨리 닳...
4                       가격도 맘에들고 다 좋아요 엄마가 쓰려고 구매했는데 만족하셔요
                               ...
13544                                       좋아요 배송빠름 메모리8G
13545                                배송이 정말 빠르고 안전하게 왔습니다
13546                                    싸게 좋은제품 구매하게 되었어요
13547                                          빠른배송 만족합니다
13548                                수요일에 주문했는데 다음날 도착했습니다
Name: text, Length: 13549, dtype: object

In [19]:
os.listdir()

['APT_Price_Seoul_Merged_2021~2025.csv',
 'APT_Price_Seoul_Merged_2021~2025.xlsx',
 'Galaxy_Book_Review_20250131.xlsx',
 'Galaxy_Book_Review_20250131_Corrected.xlsx',
 'iris.csv',
 'iris.json',
 'iris.parquet',
 'iris.tsv',
 'iris.xlsx']

In [20]:
df = pd.read_excel('Galaxy_Book_Review_20250131_Corrected.xlsx')
df.head()

,date,star,like,text,corrected
0,2025-01-13,5,3,빠르게 배송해주셔서 감사합니다 여기서 항상 사무용 노트북 주문하고 있네요 한가지 아...,빠르게 배송해 주셔서 감사합니다 여기서 항상 사무용 노트북 주문하고 있네요 한 가지...
1,2025-01-25,5,2,지난번에 구입하고 일주일 간격으로 재구매 좋아요 사장님 사은품 없습니꽈 사이즈도 성...,지난번에 구입하고 일주일 간격으로 재구매 좋아요 사장님 사은품 없습니까? 사이즈도 ...
2,2025-01-14,5,2,메모리 잘 추가되어 도착했고 윈도우 설치할때 MS 계정때문에 잠깐 어려웠는데 인터넷...,메모리 잘 추가되어 도착했고 윈도우 설치할 때 MS 계정 때문에 잠깐 어려웠는데 인...
3,2025-01-23,4,2,자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요 배터리는 좀 빨리 닳...,자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요 배터리는 좀 빨리 닳...
4,2025-01-25,5,2,가격도 맘에들고 다 좋아요 엄마가 쓰려고 구매했는데 만족하셔요,가격도 맘에 들고 다 좋아요 엄마가 쓰려고 구매했는데 만족하셔요.

In [21]:
from kiwipiepy import Kiwi

In [22]:
kiwi = Kiwi(model_type='sbg', typos='basic_with_continual_and_lengthening')

In [24]:
corrected

'복리후생으로 워라벨부터 챙기자 ᄏᄏᄏᄏ.'

In [23]:
kiwi.tokenize(corrected)

[Token(form='복리', tag='NNG', start=0, len=2),
 Token(form='후생', tag='NNG', start=2, len=2),
 Token(form='으로', tag='JKB', start=4, len=2),
 Token(form='워라밸', tag='NNG', start=7, len=3),
 Token(form='부터', tag='JX', start=10, len=2),
 Token(form='챙기', tag='VV', start=13, len=2),
 Token(form='자', tag='EC', start=15, len=1),
 Token(form='ᄏᄏᄏᄏ', tag='NNP', start=17, len=4),
 Token(form='.', tag='SF', start=21, len=1)]

In [25]:
from kiwipiepy.utils import Stopwords

In [26]:
stopwords = Stopwords()

In [27]:
stopwords.stopwords

{('ᆫ', 'ETM'),
 ('ᆫ', 'JX'),
 ('ᆫ다', 'EF'),
 ('ᆯ', 'ETM'),
 ('가', 'JKS'),
 ('같', 'VA'),
 ('것', 'NNB'),
 ('게', 'EC'),
 ('겠', 'EP'),
 ('고', 'EC'),
 ('고', 'JKQ'),
 ('과', 'JC'),
 ('과', 'JKB'),
 ('그', 'MM'),
 ('그', 'NP'),
 ('기', 'ETN'),
 ('까지', 'JX'),
 ('나', 'NP'),
 ('년', 'NNB'),
 ('는', 'ETM'),
 ('는', 'JX'),
 ('다', 'EC'),
 ('다', 'EF'),
 ('다고', 'EC'),
 ('다는', 'ETM'),
 ('대하', 'VV'),
 ('더', 'MAG'),
 ('던', 'ETM'),
 ('도', 'JX'),
 ('되', 'VV'),
 ('되', 'XSV'),
 ('들', 'XSN'),
 ('등', 'NNB'),
 ('따르', 'VV'),
 ('때', 'NNG'),
 ('때문', 'NNB'),
 ('라', 'EC'),
 ('라는', 'ETM'),
 ('로', 'JKB'),
 ('를', 'JKO'),
 ('만', 'JX'),
 ('만', 'NR'),
 ('말', 'NNG'),
 ('며', 'EC'),
 ('면', 'EC'),
 ('면서', 'EC'),
 ('명', 'NNB'),
 ('받', 'VV'),
 ('보', 'VV'),
 ('부터', 'JX'),
 ('사람', 'NNG'),
 ('성', 'XSN'),
 ('수', 'NNB'),
 ('아니', 'VCN'),
 ('않', 'VX'),
 ('어', 'EC'),
 ('어', 'EF'),
 ('어서', 'EC'),
 ('어야', 'EC'),
 ('없', 'VA'),
 ('었', 'EP'),
 ('에', 'JKB'),
 ('에게', 'JKB'),
 ('에서', 'JKB'),
 ('와', 'JC'),
 ('와', 'JKB'),
 ('우리', 'NP'),
 ('원', 'NNB'),
 ('월', 'NNB'),
 ('위하', 'VV'),
 ('으로', 'JKB'),
 ('은', 'ETM'),
 ('은', 'JX'),
 ('을', 'ETM'),
 ('을', 'JKO'),
 ('의', 'JKG'),
 ('이', 'JKC'),
 ('이', 'JKS'),
 ('이', 'MM'),
 ('이', 'NP'),
 ('이', 'VCP'),
 ('일', 'NNB'),
 ('일', 'NNG'),
 ('있', 'VV'),
 ('있', 'VX'),
 ('적', 'XSN'),
 ('제', 'XPN'),
 ('주', 'VX'),
 ('중', 'NNB'),
 ('지', 'EC'),
 ('지', 'VX'),
 ('지만', 'EC'),
 ('지역', 'NNG'),
 ('통하', 'VV'),
 ('하', 'VV'),
 ('하', 'VX'),
 ('하', 'XSA'),
 ('하', 'XSV'),
 ('한', 'MM'),
 ('화', 'XSN')}

In [28]:
kiwi.tokenize(corrected, stopwords=stopwords)

[Token(form='복리', tag='NNG', start=0, len=2),
 Token(form='후생', tag='NNG', start=2, len=2),
 Token(form='워라밸', tag='NNG', start=7, len=3),
 Token(form='챙기', tag='VV', start=13, len=2),
 Token(form='자', tag='EC', start=15, len=1),
 Token(form='ᄏᄏᄏᄏ', tag='NNP', start=17, len=4)]

In [29]:
corrected

'복리후생으로 워라벨부터 챙기자 ᄏᄏᄏᄏ.'

In [30]:
kiwi.add_user_word(word = '복리후생', tag='NNG')

True

In [32]:
tokens = kiwi.tokenize(corrected, stopwords=stopwords)

In [35]:
tokens[0]

Token(form='복리후생', tag='NNG', start=0, len=4)

In [36]:
tokens[0].form

'복리후생'

In [37]:
tokens[0].tag

'NNG'

In [39]:
tag_n = ["NNG", "NNP"]
tag_v = ['VV', 'VA', 'VV-R', 'VA-I','VV-R', 'VA-I']

In [40]:
[token.form for token in tokens if token.tag in tag_n+tag_v ]

['복리후생', '워라밸', '챙기', 'ᄏᄏᄏᄏ']

In [41]:
[token.form +'다' if token.tag in tag_v else token.form for token in tokens if token.tag in tag_n+tag_v ]

['복리후생', '워라밸', '챙기다', 'ᄏᄏᄏᄏ']

In [42]:
def tokenizer(text):
    tokens = kiwi.tokenize(text, stopwords=stopwords)
    return [token.form +'다' if token.tag in tag_v else token.form for token in tokens if token.tag in tag_n+tag_v ]

In [43]:
tokenizer(text=corrected)

['복리후생', '워라밸', '챙기다', 'ᄏᄏᄏᄏ']

In [44]:
from tqdm.notebook import tqdm

In [ ]:
morphs = []

for corrected in tqdm(df['corrected']):
    tokens = tokenizer(text = corrected)
    morphs.append(tokens)

In [47]:
morphs[:5]

[['빠르다',
  '배송',
  '감사',
  '사무',
  '노트북',
  '주문',
  '아쉽다',
  '점',
  '윈도우',
  '오피스',
  '포함',
  '버전',
  '노트북',
  '있다',
  '좋다',
  '삼성',
  '이제',
  '식',
  '나오다',
  '아쉽다'],
 ['지나다',
  '구입',
  '간격',
  '구매',
  '좋다',
  '사장',
  '사은품',
  '사이즈',
  '성능',
  '좋다',
  '사다',
  '있다',
  '사은',
  '품',
  '주다'],
 ['메모리',
  '추가',
  '도착',
  '윈도우',
  '설치',
  '계정',
  '어렵다',
  '인터넷',
  '나오다',
  '문제',
  '설치',
  '찍다',
  '사진',
  '후면',
  '모델',
  '확인',
  '차',
  '갖다',
  '집',
  '가다',
  '구매',
  '확정',
  '누르다',
  '잊다'],
 ['자격증', '프로그램', '돌아가다', '생각', '크다', '사다', '만족', '배터리', '닳다'],
 ['가격', '맘', '들다', '좋다', '엄마', '쓰다', '구매', '만족']]

In [50]:
for i in range(5):
    print(df['corrected'].iloc[i])
    print(morphs[i], end='\n\n')

빠르게 배송해 주셔서 감사합니다 여기서 항상 사무용 노트북 주문하고 있네요 한 가지 아쉬운 점은 윈도우와 오피스 포함 저렴이 버전 노트북 있으면 좋겠어요 삼성도 이젠 OS 없는 식으로 나와서 아쉽네요.
['빠르다', '배송', '감사', '사무', '노트북', '주문', '아쉽다', '점', '윈도우', '오피스', '포함', '버전', '노트북', '있다', '좋다', '삼성', '이제', '식', '나오다', '아쉽다']

지난번에 구입하고 일주일 간격으로 재구매 좋아요 사장님 사은품 없습니까? 사이즈도 성능도 딱 좋습니다 봐서 한 대 더 살 수도 있습니다 사은 품 주세요.
['지나다', '구입', '간격', '구매', '좋다', '사장', '사은품', '사이즈', '성능', '좋다', '사다', '있다', '사은', '품', '주다']

메모리 잘 추가되어 도착했고 윈도우 설치할 때 MS 계정 때문에 잠깐 어려웠는데 인터넷에 너무 잘 나와 문제 없이 설치했습니다 찍어 놓은 사진은 후면 모델 확인 차 갖고 있는 거밖에 없네요 집에 가면 구매 확정 누른다는 걸 자꾸 잊음.
['메모리', '추가', '도착', '윈도우', '설치', '계정', '어렵다', '인터넷', '나오다', '문제', '설치', '찍다', '사진', '후면', '모델', '확인', '차', '갖다', '집', '가다', '구매', '확정', '누르다', '잊다']

자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요 배터리는 좀 빨리 닳는 것 같지만요.
['자격증', '프로그램', '돌아가다', '생각', '크다', '사다', '만족', '배터리', '닳다']

가격도 맘에 들고 다 좋아요 엄마가 쓰려고 구매했는데 만족하셔요.
['가격', '맘', '들다', '좋다', '엄마', '쓰다', '구매', '만족']

In [51]:
words = ['사무용', '저렴', '재구매', '구매 확정']
tags = ['NNG']*5

In [52]:
for word, tag in zip(words, tags):
    kiwi.add_user_word(word, tag)

In [53]:
morphs = []

for corrected in tqdm(df['corrected']):
    tokens = tokenizer(text = corrected)
    morphs.append(tokens)

  0%|          | 0/13549 [00:00<?, ?it/s]

In [54]:
for i in range(5):
    print(df['corrected'].iloc[i])
    print(morphs[i], end='\n\n')

빠르게 배송해 주셔서 감사합니다 여기서 항상 사무용 노트북 주문하고 있네요 한 가지 아쉬운 점은 윈도우와 오피스 포함 저렴이 버전 노트북 있으면 좋겠어요 삼성도 이젠 OS 없는 식으로 나와서 아쉽네요.
['빠르다', '배송', '감사', '사무용', '노트북', '주문', '아쉽다', '점', '윈도우', '오피스', '포함', '저렴', '버전', '노트북', '좋다', '삼성', '이제', '식', '나오다', '아쉽다']

지난번에 구입하고 일주일 간격으로 재구매 좋아요 사장님 사은품 없습니까? 사이즈도 성능도 딱 좋습니다 봐서 한 대 더 살 수도 있습니다 사은 품 주세요.
['지나다', '구입', '간격', '재구매', '좋다', '사장', '사은품', '사이즈', '성능', '좋다', '사다', '있다', '사은', '품', '주다']

메모리 잘 추가되어 도착했고 윈도우 설치할 때 MS 계정 때문에 잠깐 어려웠는데 인터넷에 너무 잘 나와 문제 없이 설치했습니다 찍어 놓은 사진은 후면 모델 확인 차 갖고 있는 거밖에 없네요 집에 가면 구매 확정 누른다는 걸 자꾸 잊음.
['메모리', '추가', '도착', '윈도우', '설치', '계정', '어렵다', '인터넷', '나오다', '문제', '설치', '찍다', '사진', '후면', '모델', '확인', '차', '갖다', '집', '가다', '구매 확정', '누르다', '잊다']

자격증 프로그램도 잘 돌아가고 생각보다 큰 걸 샀지만 만족해요 배터리는 좀 빨리 닳는 것 같지만요.
['자격증', '프로그램', '돌아가다', '생각', '크다', '사다', '만족', '배터리', '닳다']

가격도 맘에 들고 다 좋아요 엄마가 쓰려고 구매했는데 만족하셔요.
['가격', '맘', '들다', '좋다', '엄마', '쓰다', '구매', '만족']

In [55]:
from nltk import bigrams

In [56]:
print(morphs[0])

['빠르다', '배송', '감사', '사무용', '노트북', '주문', '아쉽다', '점', '윈도우', '오피스', '포함', '저렴', '버전', '노트북', '좋다', '삼성', '이제', '식', '나오다', '아쉽다']

In [58]:
bg = bigrams(morphs[0])

In [60]:
list(bg)

[('빠르다', '배송'),
 ('배송', '감사'),
 ('감사', '사무용'),
 ('사무용', '노트북'),
 ('노트북', '주문'),
 ('주문', '아쉽다'),
 ('아쉽다', '점'),
 ('점', '윈도우'),
 ('윈도우', '오피스'),
 ('오피스', '포함'),
 ('포함', '저렴'),
 ('저렴', '버전'),
 ('버전', '노트북'),
 ('노트북', '좋다'),
 ('좋다', '삼성'),
 ('삼성', '이제'),
 ('이제', '식'),
 ('식', '나오다'),
 ('나오다', '아쉽다')]

In [64]:
bgs = []
for i in range(len(morphs)):
    bg = bigrams(morphs[i])
    bgs += list(bg)

In [65]:
len(bgs)

164608

In [66]:
pd.Series(data=bgs).value_counts().head(n=20)

(배송, 빠르다)    1828
(가성비, 좋다)    1307
(문서, 작업)      784
(라이브, 방송)     769
(가격, 대비)      699
(빠르다, 배송)     634
(빠르다, 좋다)     594
(맘, 들다)       558
(속도, 빠르다)     557
(마음, 들다)      530
(삼성, 노트북)     505
(좋다, 노트북)     443
(화면, 크다)      411
(가성비, 최고)     381
(좋다, 제품)      378
(쓰다, 좋다)      341
(좋다, 가격)      328
(노트북, 필요)     322
(다음, 날)       310
(노트북, 구매)     305
Name: count, dtype: int64

In [67]:
morphs = [[j.replace(' ','') for j in i] for i in morphs]

In [69]:
print(morphs)

[['빠르다', '배송', '감사', '사무용', '노트북', '주문', '아쉽다', '점', '윈도우', '오피스', '포함', '저렴', '버전', '노트북', '좋다', '삼성', '이제', '식', '나오다', '아쉽다'], ['지나다', '구입', '간격', '재구매', '좋다', '사장', '사은품', '사이즈', '성능', '좋다', '사다', '있다', '사은', '품', '주다'], ['메모리', '추가', '도착', '윈도우', '설치', '계정', '어렵다', '인터넷', '나오다', '문제', '설치', '찍다', '사진', '후면', '모델', '확인', '차', '갖다', '집', '가다', '구매확정', '누르다', '잊다'], ['자격증', '프로그램', '돌아가다', '생각', '크다', '사다', '만족', '배터리', '닳다'], ['가격', '맘', '들다', '좋다', '엄마', '쓰다', '구매', '만족'], ['디자인', '좋다', '폼', '나다', '쓰다', '옵션', '채우다', '쓰다', '만족'], ['좋다', '윈도우', '설치', '등', '등', '아이', '대다', '만족', '구입'], ['재구매', '사무용', '나쁘다'], ['가성비', '괜찮다', '감사'], ['포장', '튼튼하다', '받다', '소프트웨어', '관련', '옵션', '구매', '가능', '오피스', '넣다', '별도', '구매', '시간', '비용', '들다', '배송', '기다리다'], ['가볍다', '쓰다', '좋다'], ['좋다', '저렴', '가성비'], ['크다', '두께', '얇다', '사용', '좋다'], ['굿', '좋다'], ['사무용', '쓰다', '좋다', '주문'], ['엘지', '무겁다', '들다', '다니다', '힘들다'], ['감사', '쓰다'], ['빠르다', '배송', '감사'], ['빠르다', '깔끔'], ['좋다', '주말', '전', '쓰다', '데스크톱', '치우다', '노트북', '때리다'], ['구매', '제품', '만족'], ['빠르다', '배송', '감사'], ['빠르다', '안전', '배송', '굿', '굿'], ['빠르다', '배', '공', '감사'], ['아들', '들다', '다니다', '편하다'], ['무겁다', '사용', '좋다'], ['성능', '좋다', '빠르다', '만족'], ['빠르다', '배송', '좋다', '포장', '인터넷', '좋다'], ['배터리', '생각', '닳다', '빼다', '좋다'], ['배송', '빠르다', '오래전', '노트북', '쓰다', '성능', '신세계'], ['빠르다', '배송', '좋다', '굿', '굿'], ['쓰다', '일반', '사무용', '괜찮다'], ['이상', '사용'], ['좋다'], ['아버지', '선물', '드리다', '사진', '가성비', '정품', '쓰다', '좋다', '번창'], ['받다', '배송', '빠르다', '노트북', '괜찮다'], ['문서', '작업', '노트북'], ['배송', '빠르다', '제품', '좋다'], ['가격', '빠르다', '배송', '최고', '조건'], ['저렴하다', '가격', '구매', '사무용', '감사'], ['좋다', '좋다', '사용'], ['사용'], ['빠르다', '배송', '감사'], ['마음', '들다', '적극', '추천', '드리다'], ['사다', '와이프', '홈', '피시', '사용'], ['원본', '내용', '보존'], ['외관', '윈도우', '설치', '무리', '진행'], ['빠르다', '배송', '감사', '케이블', '길다', '추가', '구매', '쓰다'], ['강의', '용', '부모', '선물', '드리다', '괜찮다'], ['살다', '사용'], ['도착', '설치', '보내다'], ['성능', '만족', '가볍다', '좋다', '키', '스킨', '있다', '좋다'], ['전', '쓰다', '삼성', '갤럭시', '북', '바꾸다', '만족', '이번', '믿다', '상품', '구매', '삼성', '가성비', '좋다', '윈도우', '개봉', '설치', '오다', '편하다', '배송', '하루', '오다', '좋다'], ['배송', '빠르다', '포장', '좋다', '사용'], ['마음', '들다', '고맙다'], ['빠르다', '배송', '감사'], ['빠르다', '배송', '감사'], ['가성비', '최고', '제품', '디자인', '좋다'], ['사무용', '피시', '게임', '최고', '성비'], ['좋다', '적극', '추천', '드리다'], ['감사', '쓰다'], ['성능', '빠르다', '디자인', '깔끔'], ['빠르다', '배송', '안전', '포장', '좋다'], ['완벽'], ['빠르다', '배송', '감사'], ['쓰다', '고맙다'], ['처음', '택배', '받다', '걸레', '짝', '판매자', '택배', '박스', '택배', '박스', '안', '이중', '포장', '제품', '받다', '있다'], ['배송', '빠르다', '쓰다'], ['배송', '빠르다', '가성비', '좋다'], ['좋다', '적극', '추천', '드리다', '좋다', '적극', '추천', '드리다'], ['좋다', '무난하다'], ['디자인', '깔끔', '옛날', '노트북', '쓰다', '바꾸다', '그렇다', '상대', '가볍다', '느끼다', '가볍다', '무게', '부담', '들다', '다니다', '있다', '정도', '마이크로소프트', '로그인', '삼성', '일체', '컴퓨터', '설치', '엑셀', '연결', '좋다', '한컴', '깔다', '빠르다', '추가', '추가', '그렇다', '속도', '빠르다', '발열', '심하다', '처음', '윈도우', '한컴', '크롬', '설치', '소음', '나다', '이후', '소음', '기본', '문서', '작업', '추천', '드리다'], ['사무용', '가다', '비', '모르다', '쓰다', '봉인', '사용', '흔적', '있다'], ['사용', '만족'], ['부팅', '소리', '거슬리다', '무게', '나가다', '점', '아쉽다', '가성비', '노트북', '자체', '좋다', '시키다', '하루', '택배', '도착', '신기하다', '빠르다', '배송', '감사'], ['배송', '빠르다', '좋다', '가격', '좋다', '제품', '구매'], ['유용', '사용'], ['생각', '무겁다', '가성비', '만족'], ['배송', '빠르다', '사용'], ['노트북', '좋다', '인터넷'], ['간단하다', '동영상', '시청', '서류', '작업', '정도', '구매', '회사', '쓰다', '모델', '익숙하다', '가격', '대비', '성능', '괜찮다'], ['저렴', '사다'], ['배송', '오다'], ['받다', '빠르다', '배송', '만족'], ['서울', '그렇다', '배송', '빠르다', '놀라다', '받다', '가성비', '노트북', '불리다', '이유', '알다', '전문가', '추천', '구매', '화면', '크기', '구성', '사무용', '노트북', '만족', '화이트', '그레이', '만족', '스티커', '붙이다', '꾸미다', '귀엽다'], ['아들', '학교', '수행', '특', '쓰다', '필요', '문서', '작업', '있다', '노트북', '주문', '괜찮다', '아들'], ['가성비', '짱', '배송', '빠르다', '좋다'], ['배송', '빠르다', '화질', '성능', '맘', '들다'], ['사용', '만족', '무게', '나가다'], ['디자인', '예쁘다', '게임', '모르다', '성능', '동영상', '시청', '사무용', '쓰다', '빠르다', '배송', '빠르다', '놀라다', '정도', '감사'], ['사용'], ['배송', '빠르다', '받다', '색상', '광', '마음', '들다', '빠르다', '주식', '노트북', '사용', '사다', '쓰다', '있다', '노력'], ['가격', '좋다', '좋다', '노트북', '감사'], ['배송', '빠르다', '가성비', '짱'], ['가격', '합리', '좋다'], ['배송', '빠르다', '좋다'], ['무게', '디자인', '마음', '들다', '쓰다', '편하다', '만족', '가격', '맘', '들다', '추천'], ['깔끔', '빠르다', '좋다'], ['기대', '이상', '좋다'], ['사용', '만족'], ['좋다', '제품', '저렴', '사다'], ['색상', '디자인', '가격', '괜찮다'], ['좋다', '만족', '배송', '빠르다'], ['좋다', '굿', '굿'], ['좋다', '굿', '굿'], ['넘다', '구입', '이전', '노트북', '달라지다'], ['가성비', '노트북'], ['화질', '좋다', '출장', '동행'], ['받다', '쓰다'], ['작년', '구매', '구매', '지인', '사다', '부탁', '가성비', '좋다'], ['어머니', '좋아하다'], ['배송', '빠르다', '좋다', '감사', '사용'], ['가성비', '쓰다', '좋다', '그램', '뛰어나다', '사무용', '충분하다'], ['쓰다', '좋다'], ['회색', '좋다'], ['좋다'], ['실속', '있다', '구매', '추천'], ['배송', '안', '오다', '가성비', '사다', '좋다', '추천'], ['배송', '빠르다', '노트북', '좋다'], ['좋다', '굿', '굿'], ['좋다', '굿', '굿'], ['가격', '대비', '성능', '좋다'], ['쓰다', '하얀색', '타다', '조심', '조심', '스크린', '크다', '쓰다', '크다', '문제', '예쁘다'], ['발송', '받다', '한컴', '옵션', '알다', '착각', '한컴', '필요', '주의', '포장', '오다', '마음', '들다'], ['노트북', '삼성'], ['선물', '구매', '빠르다', '배송', '감사'], ['배송', '빠르다', '감사'], ['좋다', '추천'], ['쓰다'], ['만족', '깔끔'], ['만족', '재구매', '의사', '있다'], ['가성비', '짱'], ['배송', '빠르다', '좋다'], ['빠르다', '받다'], ['기말', '텀', '페이퍼', '작성', '노트북', '이상', '담', '주', '급하다', '구매', '노트북', '모르다', '질문', '문의', '빠르다', '친절', '답장', '날씨', '줄', '메다', '컁', '가다', '손잡이', '짧다', '직원', '들다', '다니다', '편하다', '센스', '에코', '백', '챙기다', '진심', '감사', '드리다', '수령', '후', '늦다', '언박싱', '불편', '도와주다', '직원', '진심', '감사', '드리다', '팔다'], ['쓰다'], ['배송', '빠르다', '좋다'], ['배송', '빠르다', '포장'], ['가성비', '갑', '추천'], ['재구매', '성능', '가격', '좋다'], ['질', '좋다'], ['쓰다', '굿', '굿'], ['이쁘다'], ['좋다', '제품', '저렴하다', '구입', '좋다'], ['사용'], ['아이', '인강', '사다', '만족', '쓰다', '총알', '배송', '감사'], ['인강', '사다', '좋아하다'], ['좋다', '제품', '빠르다', '배송', '감사'], ['노트북', '구입'], ['배송', '빠르다', '택배', '포장', '노트북', '성능', '좋다'], ['배송', '빠르다', '합리', '가격', '좋다', '상품', '외관', '깔끔', '예쁘다'], ['저렴', '사다', '쓰다', '배송', '빠르다'], ['인강', '크다', '사용'], ['가성비', '좋다', '편하다', '구매', '사용'], ['좋다', '선물', '사용'], ['사용', '좋다', '만족'], ['처음', '켜지다', '설명서', '충전', '후', '사용', '타입', '충전', '이동', '편리', '마우스', '유선', '불편', '무선', '구입', '학습', '좋아하다'], ['화이트', '색상', '예쁘다', '인터넷', '사진', '정리', '속도', '빠르다', '만족', '사용'], ['좋아하다', '선물', '만족', '노트북', '좋아하다'], ['조립', '나사', '오다'], ['배송', '빠르다', '좋다'], ['맘', '들다', '좋다'], ['가성비', '좋다', '뷰모님', '사다'], ['받다'], ['구동', '사용', '있다'], ['쓰다', '감사'], ['좋다', '가성비', '좋다'], ['가격', '성능', '가지다'], ['한글', '문서', '작성', '사다', '가성비', '괜찮다'], ['빠르다', '배송', '만족'], ['빠르다', '배송', '만족', '좋다', '배송', '빠르다', '포장'], ['쓰다', '좋다'], ['만족', '만족', '최고', '좋다'], ['받다', '감사'], ['가격', '빠르다', '배송', '좋다'], ['쓰다'], ['배송', '빠르다', '쓰다'], ['받다', '쓰다'], ['성능', '좋다', '쓰다'], ['살다', '쓰다'], ['인강', '사무용', '좋다'], ['배송', '빠르다', '받다'], ['받다', '고맙다'], ['배송', '빠르다', '감사'], ['제품', '무겁다'], ['빠르다', '좋다', '감사', '백신', '깔다'], ['사용'], ['가성비', '인강', '노트북', '검색', '라이브', '방송', '소식', '알다', '기다리다', '저렴', '구매', '후기', '컴맹', '다루다', '있다', '쓰다', '판단', '참다', '구입', '느리다', '괜찮다', '후기', '개인', '차', '신경', '쓰다', '사양', '성능', '바라다', '빠르다', '아무것', '설치', '사다', '만족', '있다', '가성비', '구입', '맥북', '가다', '맥북', '쓰다', '추천', '첨', '부팅', '버너', '정도', '업데이트', '그다음', '사용', '추천', '위', '목적', '원', '배송', '받다', '가성비', '좋다', '부팅', '빠르다', '인터넷', '서핑', '목적', '중간중간', '다듬다', '컴퓨터', '다루다', '예상외', '성능', '만족', '있다'], ['쓰다'], ['배송', '빠르다', '노트북', '맘', '들다'], ['사용', '만족', '가볍다', '사용', '좋다'], ['배송', '빠르다', '받다'], ['느리다', '회사', '프로그램', '설치', '사용', '쓰다'], ['가격', '대비', '나쁘다', '블루투스', '스피커', '연결', '음성', '동영상', '싱크', '맞다', '블루투스', '스피커', '사용', '포기'], ['좋다', '가성비', '최고'], ['선물', '구매', '가격', '대비', '좋다'], ['좋다', '팔다'], ['인강', '구매', '사용', '성능', '느리다'], ['가격', '성능', '디자인', '배송', '필요', '퍼펙트', '쓰다'], ['생각', '좋다'], ['재택', '근무', '제품', '구매', '가성비', '만족'], ['택배', '받다', '업데이트', '집', '웹', '서핑', '문서', '작업', '구매', '화이트', '색상', '예쁘다', '그레이', '색', '좋아하다', '고민', '화이트', '색', '선택', '깔끔', '좋다'], ['생각', '빠르다', '강의', '서핑', '괜찮다', '문제', '모르다', '업무', '프로그램', '설치'], ['문제', '쓰다'], ['사은품', '마우스', '받다', '정상', '작동', '만족'], ['속도', '느리다', '리뷰', '고민', '구매', '개인', '생각', '무게', '무겁다', '가볍다', '두껍다', '윈도우', '업그레이드', '올라가다', '버벅대', '완료', '빠르다', '돈', '쓰다', '사양', '좋다', '사다', '맞다', '문서', '작업', '비싸다', '노트북', '사다', '꺼리다', '받다', '사용', '고민', '가성비', '괜찮다', '노트북', '괜찮다', '제품'], ['사무용', '쓰다', '좋다', '사무용', '노트북', '구매'], ['아빠', '사다', '가성비', '만족', '화면', '크다', '맘', '들다'], ['할인', '행사', '저렴', '사다', '동영상', '강의', '용', '구매', '좋다', '동영상', '강의', '추천'], ['성능', '떨어지다', '멈추다'], ['문서', '작성', '인강', '좋다', '저렴하다', '가격', '유용', '사용'], ['느리다', '강의', '느리다', '느리다'], ['가격', '대비', '괜찮다', '성능', '떨어지다', '가격', '생각', '어쩌다', '일상', '용도', '사용'], ['노트북', '필요', '알아보다', '고사', '문서', '작업', '적합', '제품', '찾다', '좋다', '행사', '구성', '알차다', '문서', '작업', '필요', '추천', '추천'], ['저렴하다', '사다', '좋다', '배송', '빠르다', '좋다'], ['배송', '빠르다', '설치', '전'], ['좋다'], ['넘다', '이쁘다', '집', '엑셀', '정도', '적당하다', '버벅', '거리다', '느끼다', '과하다', '노래', '엑셀', '작업', '용도', '디자인', '맘', '들다', '확정', '누르다', '라이브', '저렴', '사다', '카드', '리더', '기도', '오다', '당첨', '화이트', '마우스', '흰색', '오다', '만족'], ['가격', '얻다'], ['굿', '굿', '굿', '좋다'], ['배송', '빠르다', '사용', '하기', '무리', '좋다'], ['선물', '드리다', '만족'], ['싸다', '지', '떡', '가성비', '노트북', '문서', '작업', '쓰다', '사다', '문서', '작업', '프로그램', '열리다', '걸리다', '크롬', '깔다', '붙잡다', '해외', '인터넷', '느리다', '정도', '속도', '돌아가다', '노트북', '포맷', '갈다', '속도', '아무것', '깔다', '새삥', '놀랍다', '노트북', '버벅거림과', '속도', '감당', '어렵다', '정도', '구형', '노트북', '빠르다'], ['상품', '도착'], ['용량', '크다', '사용', '두께', '얇다', '들다', '다니다', '나쁘다', '버벅', '경우', '있다', '돌아오다', '가격', '대비', '만족'], ['만족', '사용'], ['싸다', '사다', '디자인', '예쁘다', '성능', '괜찮다', '고민'], ['제품', '괜찮다', '배송', '빠르다', '헤비', '사용', '저렴', '제품', '선택', '셀레론', '읽다', '살다', '후회', '웹', '서핑', '문서', '작업', '정도', '가성비', '좋다', '노트북', '생각', '윈도우', '기본', '탑재', '라이브', '놓치다', '사다', '사다', '라이브', '노리다', '사은품', '받다'], ['무난하다', '가정', '문서', '작성', '피시', '쓰다'], ['숙제', '노트북', '구매', '기본', '팩', '걱정', '로딩', '빠르다', '문제', '만족', '사용'], ['느리다', '사용', '문제', '저렴하다', '구매', '사용'], ['쓰다', '엑셀', '기간', '설치'], ['가격', '할인', '저렴', '구매', '이전', '삼성', '올해', '노트북', '사용', '플러스', '예쁘다', '나오다', '파워', '팩', '주문', '사용', '공간', '속도', '빠르다', '가격', '만족', '처음', '켜다', '부분', '전화', '오다', '처리', '불편', '한글', '깔다', '방송', '참여', '손', '풍기', '받다', '책상', '올려놓다', '쓰다', '좋다', '감사', '쓰다'], ['가격', '정도'], ['좋다', '배송', '빠르다'], ['예쁘다', '좋다', '용량', '작다', '아이', '숙제', '공부', '사용', '쓰다', '가볍다', '예쁘다', '편하다'], ['버벅', '쓰다'], ['배송', '빠르다', '업데이트', '느리다'], ['저렴', '사다', '서류', '작업', '영상', '좋다'], ['방송', '혜택', '받다', '구매', '처음', '업데이트', '시간', '걸리다', '사용'], ['사이버', '대학', '다니다', '실시간', '시험', '치루다', '요긴하다', '쓰다', '맥', '기반', '컴퓨터', '윈도우', '컴퓨터', '필요', '가성비', '만족'], ['가성비', '최고', '소개', '빠르다', '느리다', '감', '사용', '문제'], ['빠르다', '배송', '감사'], ['배송', '빠르다', '설정', '사용', '느려지다', '네이버', '찾다', '시작', '프로그램', '변경', '내용', '있다', '내용', '검토', '빠르다'], ['인강', '인터넷', '쓰다'], ['아이', '선물', '가성비', '사용'], ['속도', '빠르다', '편하다', '사다'], ['아버지', '인강', '노트북', '필요', '노트북', '선택', '문제', '만족', '사용'], ['컴', '알', '한참', '업뎃'], ['쓰다', '좋다'], ['디자인', '예쁘다', '빠르다', '배송', '감사'], ['가격', '이유', '정도', '말다', '대체', '만족', '성능', '좋다', '컴퓨터', '사용', '확인', '구매', '느리다', '많다', '받다', '알다', '불편', '괜찮다', '듀얼', '코어', '충격', '전', '듀얼코어', '사용', '나오다', '상상', '사양', '확인', '잘못', '성능', '따지다', '리퍼', '상품', '구매', '낫다', '모르다', '배', '송장', '출력', '워드', '작성', '인터넷', '서핑', '정도', '라이브', '할인', '이벤트', '참여', '사은품', '전체', '만족', '라이브', '호스트', '성능', '디자인', '고장', '나다', '모르다', '상태', '유지', '가격', '대비', '만족'], ['배송', '빠르다', '포장', '노트북', '문서', '동영상', '재생', '버벅거려요'], ['빠르다', '배송', '친절', '상담', '화이트'], ['저렴하다', '구매', '검색', '사용'], ['예쁘다', '쓰다', '느리다'], ['쓰다'], ['받다', '쓰다'], ['컴', '알', '인터넷', '비교', '정도', '옵션', '눈', '익다', '가격', '대비', '괜찮다', '구매', '게임', '아이', '프린트물', '뽑다', '인터넷', '만족'], ['집', '아기', '물건', '많다', '컴퓨터', '놓다', '공간', '부담', '필요', '노트북', '알아보다', '좋다', '혜택', '구입', '있다', '만족', '주변', '노트북', '관심', '있다', '있다', '추천'], ['좋다', '굿', '굿', '굿'], ['불편', '사용'], ['검색', '문서', '기본', '인터넷', '사용', '와중', '쓰다', '노트북', '나오다', '신형', '노트북', '알다', '요즘', '나오다', '비싸다', '저렴', '노트북', '윈도', '많다', '제품', '윈도우', '설치', '지르다', '받다', '만족', '무겁다', '들다', '다니다', '정도', '집', '사용', '괜찮다', '처음', '업데이트', '작업', '랜', '선', '와이파이', '진행', '시간', '진행', '웬만하다', '랜선', '꽂다', '좋다', '오랫동안', '고장', '쓰다', '좋다'], ['라이브', '구매', '도착', '본체', '물론', '옵션', '오다', '부팅', '빠르다', '마음', '들다', '사용', '선물', '구매', '따지다', '가성비', '좋다', '라이브', '판매', '혜택', '할인', '챙기다', '그렇다', '느끼다', '속도', '나쁘다', '유튜브', '감상', '한글', '사용', '문서', '작업', '물론', '스팀', '게임', '무리', '돌아가다', '사용'], ['웹', '서핑', '사다', '만족', '가격', '착하다', '배송', '빠르다', '좋다'], ['전', '사용', '노트북', '화면', '크다', '좋다', '사양', '느리다', '버벅대', '컴맹', '원격', '서비스', '받다'], ['가격', '정도', '사양', '만족', '인강', '구입', '사양', '필요', '화이트', '디자인', '예쁘다', '화면', '넓다', '쓰다', '좋다', '생각', '무게', '나가다', '전', '들다', '다니다', '괜찮다', '라이브', '구입', '메모리', '추가', '액정', '필름', '무선', '마우스', '한컴', '받다', '라이브', '당첨', '멀티리더기', '받다', '쓰다', '알다', '만족'], ['회사', '프로그램', '설치', '구매', '빠르다', '속도', '가격', '대비', '만족', '사용'], ['문서', '작업', '위주', '사용', '제품', '발견', '구매', '만족', '좋다', '옵션', '구매', '가방', '좋다', '쓰다'], ['사용', '전', '좋다', '기분'], ['라이브', '방송', '할인', '받다', '좋다', '구성', '구매', '무겁다', '감', '디자인', '심플', '이쁘다', '고속도로', '생각', '빠르다', '만족', '대학', '과제', '쓰다', '용도', '구매', '수업', '사용', '좋다'], ['맞다', '게임', '문서', '작업', '아버님', '사다', '스펙', '용도', '쓰다', '제품', '보이다'], ['배송', '빠르다', '상품', '만족'], ['노트북', '사용', '삼성', '마우스', '휠', '소리', '나다', '빼다', '좋다'], ['아이', '교육', '문서', '인터넷', '구입', '공간', '차지', '가볍다', '문서', '파일', '인터넷', '서핑', '사용', '가격', '디자인', '만족'], ['감사', '수고'], ['인강', '사무용', '좋다'], ['디자인', '세련', '예쁘다'], ['굉장하다', '훌륭하다'], ['장점', '가격', '구매', '결정', '크다', '이유', '이전', '고사', '컴퓨터', '사다', '인강', '문서', '작성', '사용', '아깝다', '사무', '인강', '저렴', '노트북', '찾다', '추천', '노트북', '들다', '이동', '비추다'], ['사용', '느리다'], ['기존', '그램', '사용', '무게감', '휴대', '가지다', '다니다', '노트북', '말다', '집', '두다', '노트북', '사용', '좋다', '가격', '디자인', '좋다', '삼성', '노트북', '오랜만', '사용', '알다'], ['좋다', '맞다', '좋다'], ['배송', '빠르다', '가성비', '짱'], ['사무용', '가성비', '구입', '빠르다', '나쁘다'], ['사무실', '데스크톱', '운명', '공간', '차지', '노트북', '구매', '컴퓨터', '정도', '사양', '충분하다', '버벅', '리뷰', '회이트', '사다', '이쁘다', '많다', '화이트', '구매', '그레이', '후회', '현장', '타다', '쓰다'], ['만족', '인강', '문서', '작성', '사용', '괜찮다'], ['살다', '만족'], ['받다', '가성비', '좋다', '노트북'], ['업무', '좋다'], ['만족', '사용', '속도', '느리다', '문서', '작업', '가성비', '좋다', '제품'], ['가격', '라이브', '사다', '한글', '넣다', '좋다', '선물', '추첨', '받다', '이것저것', '연동', '액세서리', '좋다'], ['주문', '다음', '날', '도착', '배송', '빠르다', '속도', '그렇다', '기대', '생각', '빠르다', '만족'], ['배송', '빠르다', '좋다'], ['자세', '노트북', '개봉', '후기', '블로그', '첨부', '가성비', '훌륭하다', '배송', '빠르다', '업그레이드', '오다', '윈도우', '세팅', '쓰다', '쓰다', '휴대', '선풍기', '감사'], ['아이', '사용', '좋다', '가격', '저렴하다', '화상', '수업', '온라인', '강의', '좋다'], ['가성비', '뛰어나다', '제품'], ['후기', '작동', '특이', '사항', '불만', '사항', '상태', '윈도우', '정리', '추천', '드리다', '속도', '눈', '보이다', '달라지다'], ['고생', '사용'], ['부모', '인터넷', '서치', '인강', '문서', '작성', '찾다', '구매', '만족', '후반', '그램', '사용', '가볍다', '작업', '성능', '차이', '좋다', '라이브', '구매', '성능', '대비', '가격', '괜찮다', '구매', '만족', '다음', '구매', '번창'], ['빠르다', '배송', '감사'], ['사용'], ['선물', '재구매', '가격', '저렴하다', '가볍다', '쓰다'], ['작년', '노트북', '필요', '구입', '이번', '신랑', '필요', '구입', '젤', '좋다', '라이브', '행사', '기다리다', '당일', '시간', '까먹다', '마감', '시간', '전', '생각나다', '구입', '만족', '쓰다', '나중', '애', '필요', '사다', '오다'], ['쓰다', '무겁다', '좋다'], ['이번', '구매', '노트북', '사다', '좋다', '아이', '탭', '대신', '노트북', '구매', '아이', '인터넷', '강의', '써치', '있다', '사양', '타자', '연습', '카메라', '화상', '강의', '좋다', '탭', '휴대', '좋다', '화면', '작다', '학년', '노트북', '바꾸다', '좋다', '앞', '문제', '사용', '이번', '구매', '로그인', '오류', '뜨다', '결국', '키다', '로그인', '회수', '전화', '제품', '교환', '받다', '아이', '기다리다', '힘들다', '받다', '쓰다', '응대', '빠르다', '쓰다', '모르다', '원격', '서비스', '받다', '쓰다'], ['받다', '맞다', '리뷰', '쓰다', '화이트', '질리다', '미스틱', '그레이', '노티', '나다', '어쩌다', '생각', '좋다', '가성비', '정도', '퀄', '만족'], ['부모', '사다', '드리다', '문제', '쓰다'], ['친정', '아버지', '노트북', '필요', '알아보다', '라이브', '방송', '좋다', '가격', '구매', '아쉽다', '용량', '높다', '구매', '아쉽다', '기본', '팩', '사용', '나쁘다', '사용', '감사'], ['급하다', '노트북', '필요', '가성비', '좋다', '사용', '있다', '좋다', '삼성', '제품', '가격', '대비', '싸다', '사다', '느리다', '아쉽다', '문서', '작업', '요', '유튜브', '구매', '만족'], ['사용'], ['가성비', '굿', '굿'], ['업그레이드', '빼먹다', '구매', '용량', '부족', '경우', '추가', '금액', '지불', '업그레이드', '서비스', '좋다'], ['저렴', '디자인', '심플'], ['가격', '좋다', '성능', '좋다', '만족'], ['가성비', '좋다', '인터넷', '사용', '용도'], ['사이즈', '시원하다', '전', '쓰다', '가지다', '다니다', '작다', '사이즈', '화면', '크다', '좋다', '화이트', '색', '넘다', '크다', '이것저것', '사용', '인강', '영상', '편집', '집중', '두다', '좋다', '이것저것', '추가', '설치', '고민', '설치', '보내다', '최고', '쓰다'], ['노트북', '가성비', '좋다', '선물', '동생', '좋다'], ['라이브', '특가', '구매', '어머니', '사용', '노트북', '오래되다', '바꾸다', '만족', '디자인', '데스크탑', '부담', '업무', '책상', '놓다', '쓰다', '좋다', '사무', '업무', '학습', '좋다', '저장', '많다', '파워', '팩', '구매', '좋다', '업뎃', '사은품', '프로그램', '까다', '용량', '반', '차다', '저렴하다', '가격', '윈도우', '설치', '메모리', '업', '글', '좋다', '사은템', '받다', '생각', '배송', '빠르다', '제품', '구매', '있다', '구매'], ['업무', '구매', '노트북', '지겹다', '버벅대', '느낌', '그렇다', '속', '시원하다', '화이트', '조심', '저렴', '구입', '있다', '이렇다', '마우스', '선물', '감사', '쓰다'], ['생각', '좋다'], ['문서', '작업', '괜찮다', '빠르다', '느리다', '가격', '대비', '괜찮다'], ['느리다', '느낌', '나다', '가격', '대비', '좋다'], ['남편', '업무', '노트북', '필요', '급하다', '사다', '무난하다'], ['키보드', '전', '쓰다', '노트북', '비하다', '타자', '치다', '편하다', '터치', '감', '좋다', '화면', '넷플릭스', '시청', '안성맞춤', '인터넷', '문서', '작업', '좋다'], ['가성비', '제품', '윈도우', '깔리다', '상', '세', '란', '초기', '세팅', '가이드', '맘', '편하다', '쓰다', '지금', '쓰다', '사다', '설치', '구글', '드라이브', '사용', '마우스', '흰색', '좋다'], ['삼촌', '문서', '작업', '웹', '서핑', '원하다', '주문', '만족'], ['노트북', '오래되다', '바꾸다', '가격대', '비싸다', '쓰다'], ['배송', '빠르다', '좋다'], ['노트북', '버리다', '구매', '인강', '서류', '작성', '인터넷', '쇼핑', '사다', '여기저기', '비싸다', '가볍다', '쓰다', '부담', '격', '고민', '라이브', '방송', '주문', '램', '원뿔', '추가', '파워', '팩', '제품', '받다', '전', '걱정', '받다', '사용', '순간', '과거', '칭찬', '어제', '후회', '빠르다', '화면', '크다', '선명', '좋다', '다음', '아이', '인가', '노트북', '구매', '오다', '가다'], ['부모', '선물', '마음', '들다', '좋다', '지금', '사용', '추천'], ['삼성', '네임', '드', '가격', '대비', '괜찮다', '노트북', '속도', '빠르다', '좋다', '성능', '생각', '노트북', '사용', '용도', '적합', '느끼다', '퀄리티', '일반', '사무용', '문서', '작업', '적합', '보이다', '장점', '편리', '라이브', '특가', '구매', '한컴', '영구', '용량', '무료', '업그레이드', '만족', '상품'], ['저렴하다', '구매'], ['액', '사용', '가능'], ['마지막', '라이브', '방송', '구매', '이벤트', '당첨', '기분', '좋다', '사용', '문제', '좋다'], ['두껍다', '외관', '세련', '디자인'], ['업무', '영상', '시청', '정도', '필요', '찾다', '라방', '사다', '배송', '빠르다', '화면', '생각보다큽', '생각', '무겁다', '아쉽다', '가격', '대비', '만족'], ['화이트', '선택', '만족', '외관', '이쁘다', '화면', '좋다', '고민', '구입', '고민', '좋다', '사진', '색감', '어둡다', '실제', '화이트', '검색', '속도', '나쁘다', '사용', '좋다', '요즘', '나오다', '노트북', '비싸다', '요건', '금액', '괜찮다', '사다', '사무실', '사다', '집', '들이다'], ['넘다', '노트북', '고장', '나다', '서치', '라방', '맞다', '저렴', '구매', '주문', '담', '날', '도착', '총알', '배송', '넘다', '맘', '들다', '윈도우', '탑재', '편리', '한컴', '팩', '사용', '집안', '라이트', '사용', '장'], ['배송', '빠르다', '오다'], ['부팅', '느리다', '문서', '작성', '최고'], ['사용', '저렴', '구매'], ['좋다', '쓰다'], ['삼성', '인강', '사다', '버벅거림', '편하다', '가성비', '노트북'], ['컴퓨터', '사양', '남편', '업무', '쓰다', '모르다', '가죽', '파우치', '팔다', '쓰레기', '업무', '들다', '다니다', '창피', '정도', '허다', '접하다', '확인', '반품', '남편', '포장', '뜯다', '돈', '옵션', '묶다', '팔다', '어떻다', '생기다', '보이다', '사진'], ['사장', '상담', '물건', '가성비', '굿'], ['좋다', '굿', '굿', '디자인', '이쁘다'], ['배송', '빠르다', '설치', '쉽다', '속도', '인강', '문서', '작성', '지장', '부팅', '시간', '프로그램', '실행', '시', '초기', '약간', '로딩', '감안', '구입', '만족'], ['쓰다', '편하다', '좋다', '쓰다'], ['소리', '나다', '사용', '서비스', '맡기다', '정도', '랩탑', '쓰다', '신경', '지지', '직', '소리'], ['기존', '사무실', '플러스', '사용', '이번', '개인', '쓰다', '구매', '초기', '느리다', '크다', '느끼다', '라이브', '구매', '윈도우', '설치', '한글', '받다', '좋다', '기존', '쓰다', '프리도스', '한글', '불편', '혜택', '가격', '면', '좋다', '게임', '쓰다'], ['집', '컴', '오래되다', '문서', '작업', '노트북', '서치', '후기', '많다', '가성비', '괜찮다', '구매', '다음', '날', '라이브', '방송', '라이브', '혜택', '구매', '도착', '보장', '상품', '배송', '빠르다', '화이트', '이쁘다', '한글', '주다', '좋다', '라이브', '사은품', '오다'], ['가성비', '좋다', '가격', '대비', '쓰다', '디자인', '나쁘다', '급하다', '사다', '기다리다', '이벤트', '사다', '좋다', '생각', '드리다', '가격', '정도'], ['빠르다', '배송', '감사', '드리다', '노트북', '사다', '고민', '검색', '라이브', '특가', '방송', '가성비', '좋다', '집', '쓰다', '좋다', '구매', '쓰다', '받다', '화면', '크다', '화이트', '색상', '깔끔', '예쁘다', '만족'], ['사용'], ['가성비', '최고'], ['라이브', '방송', '특가', '구입', '아버지', '데스크톱', '바꾸다', '받다', '만족', '사진', '찍다', '보내다', '화이트', '색상', '이쁘다', '디자인', '좋다', '보이다', '문서', '작업', '검색', '괜찮다', '윈도우', '기본', '설치', '라이브', '특가', '가격', '좋다', '한컴', '기본', '제공', '괜찮다', '제품', '구매', '구매', '오다'], ['어댑터', '장남', '어뎀터', '전원', '불', '들어오다', '충전'], ['예전', '사다', '찜하다', '이번', '라이브', '방송', '구입', '하루', '배송', '오다', '한컴', '주다', '만족', '화면', '크다', '비하다', '무게', '무겁다', '쓰다'], ['처음', '개봉', '물질', '묻다', '기분', '상하다', '전원', '켜다', '사용', '문제', '보이다', '저렴', '가격', '구매', '좋다', '속도', '느리다', 

In [70]:
corpus = [' '.join(i) for i in morphs]

In [71]:
corpus

['빠르다 배송 감사 사무용 노트북 주문 아쉽다 점 윈도우 오피스 포함 저렴 버전 노트북 좋다 삼성 이제 식 나오다 아쉽다',
 '지나다 구입 간격 재구매 좋다 사장 사은품 사이즈 성능 좋다 사다 있다 사은 품 주다',
 '메모리 추가 도착 윈도우 설치 계정 어렵다 인터넷 나오다 문제 설치 찍다 사진 후면 모델 확인 차 갖다 집 가다 구매확정 누르다 잊다',
 '자격증 프로그램 돌아가다 생각 크다 사다 만족 배터리 닳다',
 '가격 맘 들다 좋다 엄마 쓰다 구매 만족',
 '디자인 좋다 폼 나다 쓰다 옵션 채우다 쓰다 만족',
 '좋다 윈도우 설치 등 등 아이 대다 만족 구입',
 '재구매 사무용 나쁘다',
 '가성비 괜찮다 감사',
 '포장 튼튼하다 받다 소프트웨어 관련 옵션 구매 가능 오피스 넣다 별도 구매 시간 비용 들다 배송 기다리다',
 '가볍다 쓰다 좋다',
 '좋다 저렴 가성비',
 '크다 두께 얇다 사용 좋다',
 '굿 좋다',
 '사무용 쓰다 좋다 주문',
 '엘지 무겁다 들다 다니다 힘들다',
 '감사 쓰다',
 '빠르다 배송 감사',
 '빠르다 깔끔',
 '좋다 주말 전 쓰다 데스크톱 치우다 노트북 때리다',
 '구매 제품 만족',
 '빠르다 배송 감사',
 '빠르다 안전 배송 굿 굿',
 '빠르다 배 공 감사',
 '아들 들다 다니다 편하다',
 '무겁다 사용 좋다',
 '성능 좋다 빠르다 만족',
 '빠르다 배송 좋다 포장 인터넷 좋다',
 '배터리 생각 닳다 빼다 좋다',
 '배송 빠르다 오래전 노트북 쓰다 성능 신세계',
 '빠르다 배송 좋다 굿 굿',
 '쓰다 일반 사무용 괜찮다',
 '이상 사용',
 '좋다',
 '아버지 선물 드리다 사진 가성비 정품 쓰다 좋다 번창',
 '받다 배송 빠르다 노트북 괜찮다',
 '문서 작업 노트북',
 '배송 빠르다 제품 좋다',
 '가격 빠르다 배송 최고 조건',
 '저렴하다 가격 구매 사무용 감사',
 '좋다 좋다 사용',
 '사용',
 '빠르다 배송 감사',
 '마음 들다 적극 추천 드리다',
 '사다 와이프 홈 피시 사용',
 '원본 내용 보존',
 '외관 윈도우 설치 무리 진행',
 '빠르다 배송 감사 케이블 길다 추가 구매 쓰다',
 '강의 용 부모 선물 드리다 괜찮다',
 '살다 사용',
 '도착 설치 보내다',
 '성능 만족 가볍다 좋다 키 스킨 있다 좋다',
 '전 쓰다 삼성 갤럭시 북 바꾸다 만족 이번 믿다 상품 구매 삼성 가성비 좋다 윈도우 개봉 설치 오다 편하다 배송 하루 오다 좋다',
 '배송 빠르다 포장 좋다 사용',
 '마음 들다 고맙다',
 '빠르다 배송 감사',
 '빠르다 배송 감사',
 '가성비 최고 제품 디자인 좋다',
 '사무용 피시 게임 최고 성비',
 '좋다 적극 추천 드리다',
 '감사 쓰다',
 '성능 빠르다 디자인 깔끔',
 '빠르다 배송 안전 포장 좋다',
 '완벽',
 '빠르다 배송 감사',
 '쓰다 고맙다',
 '처음 택배 받다 걸레 짝 판매자 택배 박스 택배 박스 안 이중 포장 제품 받다 있다',
 '배송 빠르다 쓰다',
 '배송 빠르다 가성비 좋다',
 '좋다 적극 추천 드리다 좋다 적극 추천 드리다',
 '좋다 무난하다',
 '디자인 깔끔 옛날 노트북 쓰다 바꾸다 그렇다 상대 가볍다 느끼다 가볍다 무게 부담 들다 다니다 있다 정도 마이크로소프트 로그인 삼성 일체 컴퓨터 설치 엑셀 연결 좋다 한컴 깔다 빠르다 추가 추가 그렇다 속도 빠르다 발열 심하다 처음 윈도우 한컴 크롬 설치 소음 나다 이후 소음 기본 문서 작업 추천 드리다',
 '사무용 가다 비 모르다 쓰다 봉인 사용 흔적 있다',
 '사용 만족',
 '부팅 소리 거슬리다 무게 나가다 점 아쉽다 가성비 노트북 자체 좋다 시키다 하루 택배 도착 신기하다 빠르다 배송 감사',
 '배송 빠르다 좋다 가격 좋다 제품 구매',
 '유용 사용',
 '생각 무겁다 가성비 만족',
 '배송 빠르다 사용',
 '노트북 좋다 인터넷',
 '간단하다 동영상 시청 서류 작업 정도 구매 회사 쓰다 모델 익숙하다 가격 대비 성능 괜찮다',
 '저렴 사다',
 '배송 오다',
 '받다 빠르다 배송 만족',
 '서울 그렇다 배송 빠르다 놀라다 받다 가성비 노트북 불리다 이유 알다 전문가 추천 구매 화면 크기 구성 사무용 노트북 만족 화이트 그레이 만족 스티커 붙이다 꾸미다 귀엽다',
 '아들 학교 수행 특 쓰다 필요 문서 작업 있다 노트북 주문 괜찮다 아들',
 '가성비 짱 배송 빠르다 좋다',
 '배송 빠르다 화질 성능 맘 들다',
 '사용 만족 무게 나가다',
 '디자인 예쁘다 게임 모르다 성능 동영상 시청 사무용 쓰다 빠르다 배송 빠르다 놀라다 정도 감사',
 '사용',
 '배송 빠르다 받다 색상 광 마음 들다 빠르다 주식 노트북 사용 사다 쓰다 있다 노력',
 '가격 좋다 좋다 노트북 감사',
 '배송 빠르다 가성비 짱',
 '가격 합리 좋다',
 '배송 빠르다 좋다',
 '무게 디자인 마음 들다 쓰다 편하다 만족 가격 맘 들다 추천',
 '깔끔 빠르다 좋다',
 '기대 이상 좋다',
 '사용 만족',
 '좋다 제품 저렴 사다',
 '색상 디자인 가격 괜찮다',
 '좋다 만족 배송 빠르다',
 '좋다 굿 굿',
 '좋다 굿 굿',
 '넘다 구입 이전 노트북 달라지다',
 '가성비 노트북',
 '화질 좋다 출장 동행',
 '받다 쓰다',
 '작년 구매 구매 지인 사다 부탁 가성비 좋다',
 '어머니 좋아하다',
 '배송 빠르다 좋다 감사 사용',
 '가성비 쓰다 좋다 그램 뛰어나다 사무용 충분하다',
 '쓰다 좋다',
 '회색 좋다',
 '좋다',
 '실속 있다 구매 추천',
 '배송 안 오다 가성비 사다 좋다 추천',
 '배송 빠르다 노트북 좋다',
 '좋다 굿 굿',
 '좋다 굿 굿',
 '가격 대비 성능 좋다',
 '쓰다 하얀색 타다 조심 조심 스크린 크다 쓰다 크다 문제 예쁘다',
 '발송 받다 한컴 옵션 알다 착각 한컴 필요 주의 포장 오다 마음 들다',
 '노트북 삼성',
 '선물 구매 빠르다 배송 감사',
 '배송 빠르다 감사',
 '좋다 추천',
 '쓰다',
 '만족 깔끔',
 '만족 재구매 의사 있다',
 '가성비 짱',
 '배송 빠르다 좋다',
 '빠르다 받다',
 '기말 텀 페이퍼 작성 노트북 이상 담 주 급하다 구매 노트북 모르다 질문 문의 빠르다 친절 답장 날씨 줄 메다 컁 가다 손잡이 짧다 직원 들다 다니다 편하다 센스 에코 백 챙기다 진심 감사 드리다 수령 후 늦다 언박싱 불편 도와주다 직원 진심 감사 드리다 팔다',
 '쓰다',
 '배송 빠르다 좋다',
 '배송 빠르다 포장',
 '가성비 갑 추천',
 '재구매 성능 가격 좋다',
 '질 좋다',
 '쓰다 굿 굿',
 '이쁘다',
 '좋다 제품 저렴하다 구입 좋다',
 '사용',
 '아이 인강 사다 만족 쓰다 총알 배송 감사',
 '인강 사다 좋아하다',
 '좋다 제품 빠르다 배송 감사',
 '노트북 구입',
 '배송 빠르다 택배 포장 노트북 성능 좋다',
 '배송 빠르다 합리 가격 좋다 상품 외관 깔끔 예쁘다',
 '저렴 사다 쓰다 배송 빠르다',
 '인강 크다 사용',
 '가성비 좋다 편하다 구매 사용',
 '좋다 선물 사용',
 '사용 좋다 만족',
 '처음 켜지다 설명서 충전 후 사용 타입 충전 이동 편리 마우스 유선 불편 무선 구입 학습 좋아하다',
 '화이트 색상 예쁘다 인터넷 사진 정리 속도 빠르다 만족 사용',
 '좋아하다 선물 만족 노트북 좋아하다',
 '조립 나사 오다',
 '배송 빠르다 좋다',
 '맘 들다 좋다',
 '가성비 좋다 뷰모님 사다',
 '받다',
 '구동 사용 있다',
 '쓰다 감사',
 '좋다 가성비 좋다',
 '가격 성능 가지다',
 '한글 문서 작성 사다 가성비 괜찮다',
 '빠르다 배송 만족',
 '빠르다 배송 만족 좋다 배송 빠르다 포장',
 '쓰다 좋다',
 '만족 만족 최고 좋다',
 '받다 감사',
 '가격 빠르다 배송 좋다',
 '쓰다',
 '배송 빠르다 쓰다',
 '받다 쓰다',
 '성능 좋다 쓰다',
 '살다 쓰다',
 '인강 사무용 좋다',
 '배송 빠르다 받다',
 '받다 고맙다',
 '배송 빠르다 감사',
 '제품 무겁다',
 '빠르다 좋다 감사 백신 깔다',
 '사용',
 '가성비 인강 노트북 검색 라이브 방송 소식 알다 기다리다 저렴 구매 후기 컴맹 다루다 있다 쓰다 판단 참다 구입 느리다 괜찮다 후기 개인 차 신경 쓰다 사양 성능 바라다 빠르다 아무것 설치 사다 만족 있다 가성비 구입 맥북 가다 맥북 쓰다 추천 첨 부팅 버너 정도 업데이트 그다음 사용 추천 위 목적 원 배송 받다 가성비 좋다 부팅 빠르다 인터넷 서핑 목적 중간중간 다듬다 컴퓨터 다루다 예상외 성능 만족 있다',
 '쓰다',
 '배송 빠르다 노트북 맘 들다',
 '사용 만족 가볍다 사용 좋다',
 '배송 빠르다 받다',
 '느리다 회사 프로그램 설치 사용 쓰다',
 '가격 대비 나쁘다 블루투스 스피커 연결 음성 동영상 싱크 맞다 블루투스 스피커 사용 포기',
 '좋다 가성비 최고',
 '선물 구매 가격 대비 좋다',
 '좋다 팔다',
 '인강 구매 사용 성능 느리다',
 '가격 성능 디자인 배송 필요 퍼펙트 쓰다',
 '생각 좋다',
 '재택 근무 제품 구매 가성비 만족',
 '택배 받다 업데이트 집 웹 서핑 문서 작업 구매 화이트 색상 예쁘다 그레이 색 좋아하다 고민 화이트 색 선택 깔끔 좋다',
 '생각 빠르다 강의 서핑 괜찮다 문제 모르다 업무 프로그램 설치',
 '문제 쓰다',
 '사은품 마우스 받다 정상 작동 만족',
 '속도 느리다 리뷰 고민 구매 개인 생각 무게 무겁다 가볍다 두껍다 윈도우 업그레이드 올라가다 버벅대 완료 빠르다 돈 쓰다 사양 좋다 사다 맞다 문서 작업 비싸다 노트북 사다 꺼리다 받다 사용 고민 가성비 괜찮다 노트북 괜찮다 제품',
 '사무용 쓰다 좋다 사무용 노트북 구매',
 '아빠 사다 가성비 만족 화면 크다 맘 들다',
 '할인 행사 저렴 사다 동영상 강의 용 구매 좋다 동영상 강의 추천',
 '성능 떨어지다 멈추다',
 '문서 작성 인강 좋다 저렴하다 가격 유용 사용',
 '느리다 강의 느리다 느리다',
 '가격 대비 괜찮다 성능 떨어지다 가격 생각 어쩌다 일상 용도 사용',
 '노트북 필요 알아보다 고사 문서 작업 적합 제품 찾다 좋다 행사 구성 알차다 문서 작업 필요 추천 추천',
 '저렴하다 사다 좋다 배송 빠르다 좋다',
 '배송 빠르다 설치 전',
 '좋다',
 '넘다 이쁘다 집 엑셀 정도 적당하다 버벅 거리다 느끼다 과하다 노래 엑셀 작업 용도 디자인 맘 들다 확정 누르다 라이브 저렴 사다 카드 리더 기도 오다 당첨 화이트 마우스 흰색 오다 만족',
 '가격 얻다',
 '굿 굿 굿 좋다',
 '배송 빠르다 사용 하기 무리 좋다',
 '선물 드리다 만족',
 '싸다 지 떡 가성비 노트북 문서 작업 쓰다 사다 문서 작업 프로그램 열리다 걸리다 크롬 깔다 붙잡다 해외 인터넷 느리다 정도 속도 돌아가다 노트북 포맷 갈다 속도 아무것 깔다 새삥 놀랍다 노트북 버벅거림과 속도 감당 어렵다 정도 구형 노트북 빠르다',
 '상품 도착',
 '용량 크다 사용 두께 얇다 들다 다니다 나쁘다 버벅 경우 있다 돌아오다 가격 대비 만족',
 '만족 사용',
 '싸다 사다 디자인 예쁘다 성능 괜찮다 고민',
 '제품 괜찮다 배송 빠르다 헤비 사용 저렴 제품 선택 셀레론 읽다 살다 후회 웹 서핑 문서 작업 정도 가성비 좋다 노트북 생각 윈도우 기본 탑재 라이브 놓치다 사다 사다 라이브 노리다 사은품 받다',
 '무난하다 가정 문서 작성 피시 쓰다',
 '숙제 노트북 구매 기본 팩 걱정 로딩 빠르다 문제 만족 사용',
 '느리다 사용 문제 저렴하다 구매 사용',
 '쓰다 엑셀 기간 설치',
 '가격 할인 저렴 구매 이전 삼성 올해 노트북 사용 플러스 예쁘다 나오다 파워 팩 주문 사용 공간 속도 빠르다 가격 만족 처음 켜다 부분 전화 오다 처리 불편 한글 깔다 방송 참여 손 풍기 받다 책상 올려놓다 쓰다 좋다 감사 쓰다',
 '가격 정도',
 '좋다 배송 빠르다',
 '예쁘다 좋다 용량 작다 아이 숙제 공부 사용 쓰다 가볍다 예쁘다 편하다',
 '버벅 쓰다',
 '배송 빠르다 업데이트 느리다',
 '저렴 사다 서류 작업 영상 좋다',
 '방송 혜택 받다 구매 처음 업데이트 시간 걸리다 사용',
 '사이버 대학 다니다 실시간 시험 치루다 요긴하다 쓰다 맥 기반 컴퓨터 윈도우 컴퓨터 필요 가성비 만족',
 '가성비 최고 소개 빠르다 느리다 감 사용 문제',
 '빠르다 배송 감사',
 '배송 빠르다 설정 사용 느려지다 네이버 찾다 시작 프로그램 변경 내용 있다 내용 검토 빠르다',
 '인강 인터넷 쓰다',
 '아이 선물 가성비 사용',
 '속도 빠르다 편하다 사다',
 '아버지 인강 노트북 필요 노트북 선택 문제 만족 사용',
 '컴 알 한참 업뎃',
 '쓰다 좋다',
 '디자인 예쁘다 빠르다 배송 감사',
 '가격 이유 정도 말다 대체 만족 성능 좋다 컴퓨터 사용 확인 구매 느리다 많다 받다 알다 불편 괜찮다 듀얼 코어 충격 전 듀얼코어 사용 나오다 상상 사양 확인 잘못 성능 따지다 리퍼 상품 구매 낫다 모르다 배 송장 출력 워드 작성 인터넷 서핑 정도 라이브 할인 이벤트 참여 사은품 전체 만족 라이브 호스트 성능 디자인 고장 나다 모르다 상태 유지 가격 대비 만족',
 '배송 빠르다 포장 노트북 문서 동영상 재생 버벅거려요',
 '빠르다 배송 친절 상담 화이트',
 '저렴하다 구매 검색 사용',
 '예쁘다 쓰다 느리다',
 '쓰다',
 '받다 쓰다',
 '컴 알 인터넷 비교 정도 옵션 눈 익다 가격 대비 괜찮다 구매 게임 아이 프린트물 뽑다 인터넷 만족',
 '집 아기 물건 많다 컴퓨터 놓다 공간 부담 필요 노트북 알아보다 좋다 혜택 구입 있다 만족 주변 노트북 관심 있다 있다 추천',
 '좋다 굿 굿 굿',
 '불편 사용',
 '검색 문서 기본 인터넷 사용 와중 쓰다 노트북 나오다 신형 노트북 알다 요즘 나오다 비싸다 저렴 노트북 윈도 많다 제품 윈도우 설치 지르다 받다 만족 무겁다 들다 다니다 정도 집 사용 괜찮다 처음 업데이트 작업 랜 선 와이파이 진행 시간 진행 웬만하다 랜선 꽂다 좋다 오랫동안 고장 쓰다 좋다',
 '라이브 구매 도착 본체 물론 옵션 오다 부팅 빠르다 마음 들다 사용 선물 구매 따지다 가성비 좋다 라이브 판매 혜택 할인 챙기다 그렇다 느끼다 속도 나쁘다 유튜브 감상 한글 사용 문서 작업 물론 스팀 게임 무리 돌아가다 사용',
 '웹 서핑 사다 만족 가격 착하다 배송 빠르다 좋다',
 '전 사용 노트북 화면 크다 좋다 사양 느리다 버벅대 컴맹 원격 서비스 받다',
 '가격 정도 사양 만족 인강 구입 사양 필요 화이트 디자인 예쁘다 화면 넓다 쓰다 좋다 생각 무게 나가다 전 들다 다니다 괜찮다 라이브 구입 메모리 추가 액정 필름 무선 마우스 한컴 받다 라이브 당첨 멀티리더기 받다 쓰다 알다 만족',
 '회사 프로그램 설치 구매 빠르다 속도 가격 대비 만족 사용',
 '문서 작업 위주 사용 제품 발견 구매 만족 좋다 옵션 구매 가방 좋다 쓰다',
 '사용 전 좋다 기분',
 '라이브 방송 할인 받다 좋다 구성 구매 무겁다 감 디자인 심플 이쁘다 고속도로 생각 빠르다 만족 대학 과제 쓰다 용도 구매 수업 사용 좋다',
 '맞다 게임 문서 작업 아버님 사다 스펙 용도 쓰다 제품 보이다',
 '배송 빠르다 상품 만족',
 '노트북 사용 삼성 마우스 휠 소리 나다 빼다 좋다',
 '아이 교육 문서 인터넷 구입 공간 차지 가볍다 문서 파일 인터넷 서핑 사용 가격 디자인 만족',
 '감사 수고',
 '인강 사무용 좋다',
 '디자인 세련 예쁘다',
 '굉장하다 훌륭하다',
 '장점 가격 구매 결정 크다 이유 이전 고사 컴퓨터 사다 인강 문서 작성 사용 아깝다 사무 인강 저렴 노트북 찾다 추천 노트북 들다 이동 비추다',
 '사용 느리다',
 '기존 그램 사용 무게감 휴대 가지다 다니다 노트북 말다 집 두다 노트북 사용 좋다 가격 디자인 좋다 삼성 노트북 오랜만 사용 알다',
 '좋다 맞다 좋다',
 '배송 빠르다 가성비 짱',
 '사무용 가성비 구입 빠르다 나쁘다',
 '사무실 데스크톱 운명 공간 차지 노트북 구매 컴퓨터 정도 사양 충분하다 버벅 리뷰 회이트 사다 이쁘다 많다 화이트 구매 그레이 후회 현장 타다 쓰다',
 '만족 인강 문서 작성 사용 괜찮다',
 '살다 만족',
 '받다 가성비 좋다 노트북',
 '업무 좋다',
 '만족 사용 속도 느리다 문서 작업 가성비 좋다 제품',
 '가격 라이브 사다 한글 넣다 좋다 선물 추첨 받다 이것저것 연동 액세서리 좋다',
 '주문 다음 날 도착 배송 빠르다 속도 그렇다 기대 생각 빠르다 만족',
 '배송 빠르다 좋다',
 '자세 노트북 개봉 후기 블로그 첨부 가성비 훌륭하다 배송 빠르다 업그레이드 오다 윈도우 세팅 쓰다 쓰다 휴대 선풍기 감사',
 '아이 사용 좋다 가격 저렴하다 화상 수업 온라인 강의 좋다',
 '가성비 뛰어나다 제품',
 '후기 작동 특이 사항 불만 사항 상태 윈도우 정리 추천 드리다 속도 눈 보이다 달라지다',
 '고생 사용',
 '부모 인터넷 서치 인강 문서 작성 찾다 구매 만족 후반 그램 사용 가볍다 작업 성능 차이 좋다 라이브 구매 성능 대비 가격 괜찮다 구매 만족 다음 구매 번창',
 '빠르다 배송 감사',
 '사용',
 '선물 재구매 가격 저렴하다 가볍다 쓰다',
 '작년 노트북 필요 구입 이번 신랑 필요 구입 젤 좋다 라이브 행사 기다리다 당일 시간 까먹다 마감 시간 전 생각나다 구입 만족 쓰다 나중 애 필요 사다 오다',
 '쓰다 무겁다 좋다',
 '이번 구매 노트북 사다 좋다 아이 탭 대신 노트북 구매 아이 인터넷 강의 써치 있다 사양 타자 연습 카메라 화상 강의 좋다 탭 휴대 좋다 화면 작다 학년 노트북 바꾸다 좋다 앞 문제 사용 이번 구매 로그인 오류 뜨다 결국 키다 로그인 회수 전화 제품 교환 받다 아이 기다리다 힘들다 받다 쓰다 응대 빠르다 쓰다 모르다 원격 서비스 받다 쓰다',
 '받다 맞다 리뷰 쓰다 화이트 질리다 미스틱 그레이 노티 나다 어쩌다 생각 좋다 가성비 정도 퀄 만족',
 '부모 사다 드리다 문제 쓰다',
 '친정 아버지 노트북 필요 알아보다 라이브 방송 좋다 가격 구매 아쉽다 용량 높다 구매 아쉽다 기본 팩 사용 나쁘다 사용 감사',
 '급하다 노트북 필요 가성비 좋다 사용 있다 좋다 삼성 제품 가격 대비 싸다 사다 느리다 아쉽다 문서 작업 요 유튜브 구매 만족',
 '사용',
 '가성비 굿 굿',
 '업그레이드 빼먹다 구매 용량 부족 경우 추가 금액 지불 업그레이드 서비스 좋다',
 '저렴 디자인 심플',
 '가격 좋다 성능 좋다 만족',
 '가성비 좋다 인터넷 사용 용도',
 '사이즈 시원하다 전 쓰다 가지다 다니다 작다 사이즈 화면 크다 좋다 화이트 색 넘다 크다 이것저것 사용 인강 영상 편집 집중 두다 좋다 이것저것 추가 설치 고민 설치 보내다 최고 쓰다',
 '노트북 가성비 좋다 선물 동생 좋다',
 '라이브 특가 구매 어머니 사용 노트북 오래되다 바꾸다 만족 디자인 데스크탑 부담 업무 책상 놓다 쓰다 좋다 사무 업무 학습 좋다 저장 많다 파워 팩 구매 좋다 업뎃 사은품 프로그램 까다 용량 반 차다 저렴하다 가격 윈도우 설치 메모리 업 글 좋다 사은템 받다 생각 배송 빠르다 제품 구매 있다 구매',
 '업무 구매 노트북 지겹다 버벅대 느낌 그렇다 속 시원하다 화이트 조심 저렴 구입 있다 이렇다 마우스 선물 감사 쓰다',
 '생각 좋다',
 '문서 작업 괜찮다 빠르다 느리다 가격 대비 괜찮다',
 '느리다 느낌 나다 가격 대비 좋다',
 '남편 업무 노트북 필요 급하다 사다 무난하다',
 '키보드 전 쓰다 노트북 비하다 타자 치다 편하다 터치 감 좋다 화면 넷플릭스 시청 안성맞춤 인터넷 문서 작업 좋다',
 '가성비 제품 윈도우 깔리다 상 세 란 초기 세팅 가이드 맘 편하다 쓰다 지금 쓰다 사다 설치 구글 드라이브 사용 마우스 흰색 좋다',
 '삼촌 문서 작업 웹 서핑 원하다 주문 만족',
 '노트북 오래되다 바꾸다 가격대 비싸다 쓰다',
 '배송 빠르다 좋다',
 '노트북 버리다 구매 인강 서류 작성 인터넷 쇼핑 사다 여기저기 비싸다 가볍다 쓰다 부담 격 고민 라이브 방송 주문 램 원뿔 추가 파워 팩 제품 받다 전 걱정 받다 사용 순간 과거 칭찬 어제 후회 빠르다 화면 크다 선명 좋다 다음 아이 인가 노트북 구매 오다 가다',
 '부모 선물 마음 들다 좋다 지금 사용 추천',
 '삼성 네임 드 가격 대비 괜찮다 노트북 속도 빠르다 좋다 성능 생각 노트북 사용 용도 적합 느끼다 퀄리티 일반 사무용 문서 작업 적합 보이다 장점 편리 라이브 특가 구매 한컴 영구 용량 무료 업그레이드 만족 상품',
 '저렴하다 구매',
 '액 사용 가능',
 '마지막 라이브 방송 구매 이벤트 당첨 기분 좋다 사용 문제 좋다',
 '두껍다 외관 세련 디자인',
 '업무 영상 시청 정도 필요 찾다 라방 사다 배송 빠르다 화면 생각보다큽 생각 무겁다 아쉽다 가격 대비 만족',
 '화이트 선택 만족 외관 이쁘다 화면 좋다 고민 구입 고민 좋다 사진 색감 어둡다 실제 화이트 검색 속도 나쁘다 사용 좋다 요즘 나오다 노트북 비싸다 요건 금액 괜찮다 사다 사무실 사다 집 들이다',
 '넘다 노트북 고장 나다 서치 라방 맞다 저렴 구매 주문 담 날 도착 총알 배송 넘다 맘 들다 윈도우 탑재 편리 한컴 팩 사용 집안 라이트 사용 장',
 '배송 빠르다 오다',
 '부팅 느리다 문서 작성 최고',
 '사용 저렴 구매',
 '좋다 쓰다',
 '삼성 인강 사다 버벅거림 편하다 가성비 노트북',
 '컴퓨터 사양 남편 업무 쓰다 모르다 가죽 파우치 팔다 쓰레기 업무 들다 다니다 창피 정도 허다 접하다 확인 반품 남편 포장 뜯다 돈 옵션 묶다 팔다 어떻다 생기다 보이다 사진',
 '사장 상담 물건 가성비 굿',
 '좋다 굿 굿 디자인 이쁘다',
 '배송 빠르다 설치 쉽다 속도 인강 문서 작성 지장 부팅 시간 프로그램 실행 시 초기 약간 로딩 감안 구입 만족',
 '쓰다 편하다 좋다 쓰다',
 '소리 나다 사용 서비스 맡기다 정도 랩탑 쓰다 신경 지지 직 소리',
 '기존 사무실 플러스 사용 이번 개인 쓰다 구매 초기 느리다 크다 느끼다 라이브 구매 윈도우 설치 한글 받다 좋다 기존 쓰다 프리도스 한글 불편 혜택 가격 면 좋다 게임 쓰다',
 '집 컴 오래되다 문서 작업 노트북 서치 후기 많다 가성비 괜찮다 구매 다음 날 라이브 방송 라이브 혜택 구매 도착 보장 상품 배송 빠르다 화이트 이쁘다 한글 주다 좋다 라이브 사은품 오다',
 '가성비 좋다 가격 대비 쓰다 디자인 나쁘다 급하다 사다 기다리다 이벤트 사다 좋다 생각 드리다 가격 정도',
 '빠르다 배송 감사 드리다 노트북 사다 고민 검색 라이브 특가 방송 가성비 좋다 집 쓰다 좋다 구매 쓰다 받다 화면 크다 화이트 색상 깔끔 예쁘다 만족',
 '사용',
 '가성비 최고',
 '라이브 방송 특가 구입 아버지 데스크톱 바꾸다 받다 만족 사진 찍다 보내다 화이트 색상 이쁘다 디자인 좋다 보이다 문서 작업 검색 괜찮다 윈도우 기본 설치 라이브 특가 가격 좋다 한컴 기본 제공 괜찮다 제품 구매 구매 오다',
 '어댑터 장남 어뎀터 전원 불 들어오다 충전',
 '예전 사다 찜하다 이번 라이브 방송 구입 하루 배송 오다 한컴 주다 만족 화면 크다 비하다 무게 무겁다 쓰다',
 '처음 개봉 물질 묻다 기분 상하다 전원 켜다 사용 문제 보이다 저렴 가격 구매 좋다 속도 느리다 많다 쓰다 크다 지장 싸다 좋다 망설이다 구매 후회 사용',
 '좋다 쓰다',
 '느리다 감 게임 문서 작업 사다 정도 만족 주인 고양이 좋아하다',
 '가격 좋다 노트북 구입 만족 디자인 가격 대비 성능 훌륭하다 노트북 경우 카메라 화면 하단 반면 제품 카메라 화면 상단 위치 점 좋다',
 '좋다 맞다 좋다 좋다 좋다 좋다 좋다',
 '배송 빠르다 처음 느리다 생각 들다 업데이트 끝나다 키다 괜찮다 사무용 유튜브 지장',
 '빠르다 배송 감사',
 '지금 사용',
 '배송 빠르다 받다 생각 무게 속도 늦다 감 있다 학습 인강 구매 가격 대비 괜찮다 이것저것 다운 받다 동안 소음 동안 사라지다 불안',
 '노트북 가볍다 화이트 디자인 이쁘다 작업 사다 화면 크다 사용',
 '라이브 방송 주문 저렴 살다 있다 집 인강 가성비 사은품 손 선풍 쓰다',
 '가성비 최고 좋다',
 '좋다 좋다 초기 설치 걸리다 가볍다 좋다',
 '이번 노트북 구입 리뷰 남기다 아버지 쓰다 컴퓨터 고장 나다 알아보다 저렴하다 괜찮다 스펙 가지다 노트북 구입 배송 노트북 상태 좋다 수동 이상 다음 기회 구매 없어지다',
 '빠르다 배송 제품 상태 양호',
 '배송 굿 사무용',
 '좋다 상품 배송 감사',
 '배송 빠르다 포장 제품 가격 대비 만족 업무 쓰다 좋다 인강 유튜브 동영상 좋다 가성비 최고',
 '느리다 인강 무리',
 '컴퓨터 속도 괜찮다 쓰다',
 '사은품 받다 겉 박스 찌그러지다 작동',
 '업무 문서 작성 사용 기본 노트북 검색 할인 쿠폰 저렴 가격 구입 처음 속도 느리다 부분 연결 블로그 설명 처리 정상 속도 회복 사용 문제 보이다 윈도우 설치 좋다 화면 크다 노안 오다 업무 도움 사은품 보내다 노트북 파우치 삼성 마우스 마음 들다 색깔 센스 있다 맞추다 보내다 박스 동봉 보내다 믿음 가다 덕분 좋다 가격 사용 감사',
 '노트북 고르다 고민 고르다 고르다 최종 구입 배송 빠르다 크기 원하다 사이즈 구성 좋다 모바일 전자 제품 사다 처음 걱정 상품 평 밑 사다 괜하다 기우 사용 노트북 비하다 크기 무게 나가다 좋다 장고 끝 좋다 선택 민족 화면 보호 필름 거지 붙이다 보이다 구매 가능',
 '집 폰 한계 있다 많다 기능 필요 기본 기능 필요 가격 라이브 특가 사다 저렴하다 한컴 무료 받다 운 좋다 살다 노트북 겉 괜찮다 안 생각 이쁘다 깔끔 설치 쉽다 좋다',
 '디자인 예쁘다 사무 작업 좋다 윈도우 설치 편하다',
 '쓰다',
 '받다 깔끔 한컴 오피스 설치 오다 설치 사용',
 '생각 빠르다 좋다',
 '제품 포장 좋다',
 '컴퓨터 자격증 준비 이것저것 찾아보다 가성비 괜찮다 추천 구매 자다 고장 쓰다',
 '쓰다 좋다',
 '엄마 단순 문서 작업 쓰다 빠르다 가볍다 좋다 컴퓨터 모르다 기능 모르다 스펙 가격 카톡 쇼핑 비 전용 사이트 좋다',
 '모르다 제품 많다 대중 사용 노트북 스테디셀러 베스트 셀러 믿다 사용 만족 사용',
 '배송 빠르다',
 '문서 작업 노트북 찾다 라이브 쇼핑 타이밍 맞다 한컴 포함 상품 좋다 가격 사다 화면 크다 아버지 좋아하다',
 '배송 빠르다 이틀 사용 만족 인강 문서 작업 좋다 라이브 방송 남다 구매 저렴 혜택 좋다 구매 라이브 방송 주문 추천 문 답변 감사',
 '중학 아이 온라인 수업 인강 구매 생각 그래픽 괜찮다 맘 들다 저렴 살다',
 '배송 빠르다 안전 오다 좋다 노트북 쓰다 쓰다 화질 좋다 빠르다 좋다 추가 완전 가성비 노트북 생각 가볍다 숫자 키 패드 있다 좋다 쓰다 인강 문서 완전 추천 한글 설치 점',
 '라이브 구매 할인 받다 사은품 당첨',
 '만족 사용',
 '합리 가격 만족 집 두다 쓰다 데스크톱 터지다 급하다 사다 최고',
 '딸 선물 좋다',
 '하루 빠르다 배송 친절 답변 감사',
 '좋다 배송 빠르다 가격 맘 들다 라이브 노트북 인원 랑 지르다 쓰다',
 '저렴 배송 빠르다 단지 많다 귀찮다 적응',
 '발열 심하다 쓰다',
 '라 방 사다 가성비 최고 신랑 마음 들다 감사',
 '문제 쓰다',
 '세팅 깔끔 지다',
 '가격 살다 느리다 평 많다 듕귁',
 '재택근무 사다 쓰다',
 '속도 빠르다 사무 작업 인강 살다 크다 불편 무게 있다 가성비 좋다',
 '가격 맞다 수준 성능 크다 기대 괜찮다',
 '용도 맞다 구매 사용 좋다',
 '배송 빠르다 안전 오다 작동',
 '문서 작업 제품 가격 대비 나쁘다 세팅 쓰다',
 '디자인 예쁘다 좋다 가볍다 좋다 가격 저렴하다 비하다 성능 괜찮다 좋다 상품 감사',
 '가성비 맞다 세팅',
 '라이브 특가 뜨다 고민 사다 라이브 질문 알리다 살다 믿다 만족 용량 추가 살다 아쉽다',
 '쓰다 가성비 갑',
 '디자인 좋다 속도 아쉽다',
 '가격 대비 훌륭하다 이상 쓰다 삼성 믿음 가다',
 '좋다 쓰다',
 '데스크톱 늦다 버벅거려서 인터넷 서핑 괜찮다',
 '사용 편리 좋다 추천',
 '대 구입 전문가 작업 필요 이상 퇴근 후 사무 처리 아이 인강 시 조금 부족 배송 칼 배송 합리 가격 만족',
 '인강 노트북 서치 가격 삼성 브랜드 상품 평 좋다 라이브 방송 가성비 좋다 대기 구매 인 강 언박싱 생각 해 선풍기 들다 땡 잡다 기분 감사',
 '쓰다 무겁다 빼다 좋다',
 '부모 쓰다 구매 가격 대비 성능 만족 무게 무겁다 부모 만족 최고',
 '디자인 심플 성능 가성비 괜찮다',
 '배송 오다 노트북 좋다 화면 사진 찍다 사진 번지다 나오다 휴대 무겁다 배터리 길다 가다 좋다 인강 문서 작업 사다 한글 제공 주다 좋다',
 '배송 빠르다 모델 쓰다 선물 재구매',
 '윈도우 업데이트 윈도우 날아가다 수리 받다 오다',
 '갤럭시 북 이온 쓰다 잦다 수리비 메인 보드 고장 가성비 노트북 바꾸다 무게감 이온 비하다 무겁다 휴대 떨어지다 저렴 좋다 배송 빠르다',
 '삼성 공식 파트너 믿다 구매 저렴 가격 대비 만족 화면 키보드 크다 이용 불편 인강 사무용 쓰다 좋다 사은품 받다 파우치 색상 두께 마음 들다 용량 추가 맞다 방문 수령 직원 친절 만족 구매 마무리 다음 구매 감사',
 '배송 다음 날 받다 쓰다',
 '노트북 좋다 만족 액정 보호 필름 실패 사용',
 '결제 총알 발송 배송 바쁘다 켜다 외관 예쁘다 집 쓰다 용도 가성비 좋다 선택 선택 기대',
 '설명 정확 상태 좋다',
 '사용 감사',
 '학습 노트북 필요 알아보다 친구 추천 구매 라방 사다 사은품 혜택 많다 기다리다 사다 방송 선택 많다 정신없다 주문 색상 고민 그레이 화이트 변경 요청 비싸다 사다 아쉽다 설치 방 안 두다 좋다 화이트 색상 예쁘다 무게 나쁘다 요즘 시대 마우스 유선 집 있다 쓰다 아이 공부 업데이트 좋다',
 '전원 키다 넘다 걸리다 꺼지다 업데이트 빠르다',
 '이쁘다 좋다 컴퓨터 핸드폰 삼성 최고',
 '필요 업 그레이 구매',
 '지나다 화면 사용 나가다 들다 올레 문제 생기다 알다 삼성 가져가다 기계 문제 윈도우 사용 후 종료 닫다 업데이트 이루어지다 설명 오다 사용 사용 화면 나가다 글 보이다 후기 적다 참고',
 '사무용 쓰다',
 '노트북 마음 들다 라이브 방송 저렴 구매 마음 들다 한컴 오피스 증정 사무용 쓰다 사다 만족 한컴 깔리다 간단하다 있다 좋다 윈도우 깔리다 만족 여행 가다 전 주문 주문 다음 날 배송 오다 핸드폰 핫 스폿 연결 회사 가져가다 유선 인터넷 연결 후 삼성 서비스 상담 키보드 버튼 누르다 문의 드리다 채팅 상담 원격 문제 해결 앞 문제 생기다 해결 가능 완전 만족 사용 편리 만족',
 '비 오다 날 배송 상품 상자 비 방울 묻다 안전 배송 노트북 마우스 어댑터 상품 구매 상품 상쇠 설명 나오다 성품 포장 배송 기본 구성 구매 집 동영상 시청 문서 작업 일반 사용 가성비 뛰어나다 제품',
 '라이브 저렴 화이트 모델 파워 팩 램 돌려받다 구성 한컴 오피스 팩 유선 마우스 포함 화면 보호 필름 기본 라이브 이벤트 멀티리더기 당첨 사무용 작업 필요 어머니 노트북 선물 드리다 무게감 사무실 두다 쓰다 괜찮다',
 '맞다 좋다 좋다 좋다',
 '저렴하다 구매',
 '동생 선물 사다 게임 돌아가다 모 만족',
 '당일 배송 다음 날 받다 원하다 성능 저렴 가격 만족',
 '라이브 가성비 사다 만족 한컴 영구 소장 받다 윈도우 깔리다 문서 작업 서치 살다 무겁다 프로그램 돌리다 에이에스 삼성 걱정 유연 선 마우스 선택 노트북 색상 맞다 들다 단점 무겁다 들다 다니다 용도 괜찮다 갖다 다니다 인강 학생 무겁다 있다',
 '가성비 좋다 노트북 색감 예쁘다 인강 넷플 유튜브 최적화',
 '배송 빠르다 좋다 심플 마음 들다',
 '배송 오다 주문 출고 다음 날 도착 노트북 예상 것보다큽 가로 정도 첨부 사진 정도 사이즈 예상 화면 크다 깔끔 영상 감상 좋다 업데이트 끝나다 노트북 자체 버퍼 링 조금 노트북 발열 있다 사소하다 단점 화면 가격 나쁘다 밖 작업 사용 적절하다 만족',
 '가성비 좋다 사용',
 '재구매 후 이상 사용 후기 남기다 어른 가볍다 컴퓨터 배우다 이전 구매 드리다 주문 라이브 쇼핑 방송 알림 맞추다 그때 구매 이벤트 한컴 받다 있다 라이브 이벤트 참여 있다 기본 구성 좋다 메모리 업그레이드 라이브 사다 기본 저렴 이득 마우스 증정 그레이 사다 검정 마우스 화이트 사다 희다 마우스 주다 색 맞추다 센스 컬러 미묘하다 키 감 다르다 느낌 들다 키 감 가볍다 괜찮다 광 세련 느낌 추가 장착 쉽다 보이다 인치 자리 있다 아쉽다 열다 쉽다 만들다 교체 가이드 첨부 있다 사용 후기 남기다 미루다 업그레이드 전 추가 장착 후 후기 남기다',
 '라이브 방송 구매 많다 혜택 저렴하다 가격 구매',
 '남자 친구 선물 좋아하다 갤럭시 동기화 좋다 디자인 예쁘다 공부 최고 키 감 좋다 터치 패드 크다 편하다 배송 빠르다 오다 좋다 자판 크다 최고 무겁다 들다 다니다 불편 화이트 고민 화이트 사다 실물 예쁘다',
 '빠르다 좋다 램 업 글',
 '라이브 방송 구매 이벤트 당첨 사용 편하다 좋다',
 '빠르다 배송 감사',
 '쓰다 구입 후 가격 떨어지다 속',
 '맘 들다 색깔 좋다 파워 팩 빠르다',
 '윈도우 기본 신상 제품 가성비 좋다 셀룰런 걱정 시리즈 차이 모르다 사무용 쓰다 무리 제품',
 '사무용 무난하다 쓰다 좋다',
 '가성비 좋다 인터넷 문서 작업 색깔 고급 가볍다',
 '가격 대비 속도 그렇다 만족 화질 떨어지다',
 '전 쓰다 노트북 고장 나다 오래되다 바꾸다 노트북 속도 나다 만족 디자인 마음 들다 가성비 만족 쉽다 스피커 음질 좋다 좋다 생각 말다 만족',
 '아이 사용 노트북 검색 품 사다 찜 며칠 넘다 사용 노트북 화면 흔들리다 구매 라이브 방송 알림 맞추다 방송 시간 방송 채팅 창 스텝 친절 답 주다 사전 알다 노트북 결정 있다 윈도 설치 점 좋다 한컴 오피스 팩 램 업그레이드 마우스 보호 필름 라이브 구매 인증 이벤트 받다 필요 만족 노트북 창 착하다 분리 삼성 노트북 장착 쉽다 장착 배송 하루 도착 아이 구매 구입 아이 구매 만족',
 '문서 작성 구매 좋다',
 '가성비 좋다 노트 삼성 윈도우 설치 가능 복구 가능 쓰다',
 '가볍다 사용 용 사다 선물 드리다',
 '쓰다 좋다 부모 사다 인강 부모 작업 좋다 부모 친구 구입 물어보다',
 '감사 좋다 가격 대비 가성비 미치다 강추강추추추',
 '아빠 게임 구매 구동 좋다',
 '고민 결정 라이브 사다 좋다',
 '쓰다 배터리 달다 충전 기 꼽다 사용',
 '화이트 변경 오다 예쁘다 윈도우 깔리다 좋다 라이브 많다 혜택 받다 있다 좋다',
 '엄마 주문 쓰다 사무용 느리다 쓰다 무게 무겁다',
 '좋다 만족 흡족',
 '라이브 특가 구매 구매 생각 점 화면 사이즈 가격 속도 일반 정도 사무 업무 동영상 시청 웹 서핑 만족',
 '배송 하루 오다 업뎃 빠르다 빠르다 사용 있다 유튜브 넷플 사다 좋다',
 '좋다 상품 저렴 구매',
 '처음 모르다 느리다 느리다',
 '쓰다 부팅 속도 느리다',
 '사용 좋다 사용',
 '배송 늦다 노트북 깔끔 쓰다 알다 크다 문제',
 '라이브 알림 설정 기다리다 한글 무료 증정 좋다 라이브 구매 인증 사은품 보내다 기본 문서 작업 사다 그레이 색상 이쁘다 릭스 폰트 설치 후 폰 깔다 카톡 글씨체 이쁘다 기분 좋다',
 '어제 방 구매 로켓 빠르다 오늘 받다 택배 겉 박스 부분 구겨지다 노트북 내부 괜찮다 의심 포장 인하다 내부 이상 친절 설명 덕분 프로그램 설치 무난하다 끝내다 앞 사용 주변 가성비 노트북 찾다 적극 홍보',
 '재택근무 구매 만족',
 '빠르다 배송 한컴 오피스 제공 윈도 장착 구동 느리다',
 '싸다 가격 만족',
 '디자인 성능 화면 크기 좋다 무겁다 사무실 보조 컴퓨터 쓰다 가격 대비 만족',
 '배송 받다 작동 생각 가볍다 사용 좋다',
 '아버지 사무용 필요 구매 배송 빠르다 안전 받다 속도 빠르다 업무 쓰다 괜찮다 팔다',
 '인강 한글 작업 무난하다 추가 구매 가죽 파우치 사다 노트북 넣다 노트북 구겨지다 노트북 좋다',
 '라이브 특가 싸다 구입 문서 작성 구매 한글 프로그램 제공 사용',
 '노트북 저렴하다 구매',
 '필요 타임 적당하다 가격 사다 화면 크다 검색 좋다',
 '엄마 생신 선물 드리다 저번 쓰다 노트북 가볍다 마우스 사다 느낌 좋다 가성비 좋다 상품',
 '마음 들다 받다 감사',
 '얇다 가성비 좋다 웹 서핑 사다',
 '좋다 하루 배송 오다 품질 좋다',
 '좋다 좋다 선물',
 '배송 빠르다 제품 상쇄 설명 깔끔',
 '윈도우 업데이트 부팅 시간 걸리다 걱정 완료 빠르다 작동 좋다 노트북 필요 라이브 특가 사다 만족 사용 알다 현재 만족',
 '생애 노트북 삼성 믿다 사다 화이트 예쁘다 한컴 사용',
 '화면 크다 마우스 주다 가성비 갑 삼성 폰 쓰다 연동 편하다 좋다 업무 개인 블로그 쓰다 용 구매 만족',
 '무겁다 괜찮다',
 '와이프 선물 사다 좋다',
 '도착 빠르다 믿다 구매 감사',
 '도착 빠르다 믿다 구매 감사',
 '버벅 문서 작성 좋다 쓰다 달 리뷰 올리다',
 '라 방 구매 집 인터넷 문서 작업 구매 가격 퀄이 만족 배송 빠르다 오다 좋다 설치 어렵다 사용 가성비 있다 노트북 추천',
 '학습 구매 속도 빠르다 만족',
 '노트북 알다 인터넷 서치 문서 작업 인강 사용 예정 비싸다 필요 만족 작동 생각 속도 빠르다 저렴 라이브 방송 살다 조건 추천 사용',
 '사무용 노트북 필요 급하다 사다 배송 빠르다 노트북 나쁘다 후기 반응 갈리다 걱정 괜찮다 속도 괜찮다 좋다',
 '집 업무 구입 속도 맘 들다 디자인 괜찮다 비싸다 컴퓨터 사다 좋다 기능 모르다 사용 사용 필요 쓰다 불편 무게감 무겁다 출장 가능 쓰다',
 '부모 선물 드리다 사다 사용 성능 모르다 좋다',
 '남편 생일 선물 사다 맘 들다 라이브 사다 혜택 좋다 좋다',
 '사용',
 '사용 좋다 하얀색 좋다',
 '배송 빠르다 문서 작성 동영상 용도 최고',
 '디자인 클래식 사용 좋다 삼성 노트북 저렴 최고',
 '디자인 이쁘다 가볍다 간단 사무용 좋다',
 '전 쓰다 랩탑 비하다 무겁다 가성비 좋다 쓰다 배송 하루 오다',
 '간편하다 쓰다 좋다 타자 치다 자판 사이즈 맞다',
 '인터넷 서핑 동영상 가성비 짱',
 '쓰다',
 '처음 속도 느리다 쓰다 속도 빠르다 적응 저렴하다 사다 탓 쓰다',
 '가성비 갑 세팅 끝나다 좋다',
 '배송 오다 화면 키보드 이상 구매 쓰다 만족',
 '좋다 살다',
 '부모 서류 알바 받다 아기 컴퓨터 방 아기 불편 노트북 문서 작업 알아보다 라이브 들어가다 램 기가 증정 한글 주다 추가 사다 이유 사다 알바 노트북 값 벌다 집 삼성 갤탭 있다 듀얼 스크린 연결 쓰다 편하다 좋다 노트북 단점 찾다 문서 크다 기대 듀얼 연결 무선 마우스 크다 딜레이 길다 흠 꿀 팁 화면 복제 펜 쓰다 있다 장점',
 '라이브 방송 저렴하다 사다 가성비 좋다 노트북',
 '좋다 좋다',
 '빠르다 배송 감사',
 '가성비 노트북 구매 윈11 램 쓰다 느리다 있다',
 '전날 주문 다음 날 도착 배송 빠르다 색깔 그레이 선택 좋다 사양 업그레이드 받다 속도 괜찮다 전반 만족',
 '사무실 문서 작업실 좋다',
 '집 사용 좋다',
 '업무 쓰다 사다 무게감 들다 다니다 무리 쓰다 사다 사용 프로그램 설치 느리다 느낌 받다 켜지다 로딩 늦다 쓰다',
 '사용 만족 만족',
 '가성비 노트북 찾다 제품 구입 받다 속도 빠르다 가성비 좋다',
 '마음 들다 속도 느리다',
 '가성비 굿 굿 좋다',
 '가격 구입 사용 불편 사용 좋다',
 '문서 작업 구매 크다 불편',
 '가격 품질 성능 기능 만족 라이브 이벤트 사은품 좋다 총알 배송 감사 사무용 적극 추천 드리다 디자인 심플 가볍다 좋다 속도 빠르다 화질 좋다 세다',
 '속도감 떨어지다 문서 작업 문제 가격 대비 괜찮다 게임 불편 있다 좋다',
 '색깔 고민 그레이 광 세련 맘 들다 한글 팩 윈도우 깔리다 문서 작업 불편 고민 파워 팩 파워 팩 좋다 한글 필요 파일 깔다 사용',
 '집 사용 하기 좋다',
 '씨피유 튀다',
 '사용 가성비 좋다 노트북',
 '간헐 쓰다',
 '배송 빠르다 좋다',
 '삼성 노트북 사은품 받다 배송 빠르다 좋다 앞 쓰다 색깔 예쁘다 컴퓨터 작동 인강 문서 편집 쓰다 예정 가격 삼성 브랜드 좋다',
 '삼성 좋다',
 '가성비 노트북 찾다 라이브 방송 구매 용량 부족 업그레이드 팩 무겁다 느리다 가성비 정도 쓰다 생각 디자인 예쁘다',

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

In [76]:
cv = CountVectorizer(min_df = 0.01)

In [77]:
dtm = cv.fit_transform(corpus).toarray()

In [78]:
dtm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [80]:
dtm = pd.DataFrame(data = dtm, columns=cv.get_feature_names_out())
dtm

,가격,가능,가다,가볍다,가성비,감사,강의,걱정,걸리다,검색,...,하루,한글,한컴,할인,혜택,화면,화이트,화질,후기,흰색
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13544,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13546,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13547,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13548,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [81]:
dtm.sum().sort_values(ascending=False).head(n=20)

좋다     9935
노트북    5433
구매     4260
쓰다     4133
사용     4059
빠르다    4015
배송     3723
만족     3017
가성비    2925
가격     2816
사다     2736
받다     2038
제품     1761
있다     1598
라이브    1580
들다     1509
생각     1358
삼성     1304
디자인    1270
구입     1253
dtype: int64